return {
  ['Bronze bar'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'rs-bar',
    ['stack_size'] = 100,
    ['order'] = 1,
    ['vanilla_name'] = 'copper-plate',
    ['rs_name'] = 'bronze_bar',
    ['name'] = 'rs-bronze-bar',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsSmithing__/graphics/icons/auto_generated/bronze_bar.png',
    ['icon_size'] = 32,
    ['high_alch'] = 27,
    ['low_alch'] = 18,
    ['examine'] = 'Used in Smithing (1).',
  },
  ['Iron bar'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'rs-bar',
    ['stack_size'] = 100,
    ['order'] = 10,
    ['vanilla_name'] = 'iron-plate',
    ['rs_name'] = 'iron_bar',
    ['name'] = 'rs-iron-bar',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsSmithing__/graphics/icons/auto_generated/iron_bar.png',
    ['icon_size'] = 32,
    ['high_alch'] = 35,
    ['low_alch'] = 23,
    ['examine'] = 'Used in Smithing (10).',
  },
  ['Steel bar'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'rs-bar',
    ['stack_size'] = 100,
    ['order'] = 20,
    ['vanilla_name'] = 'steel-plate',
    ['rs_name'] = 'steel_bar',
    ['name'] = 'rs-steel-bar',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsSmithing__/graphics/icons/auto_generated/steel_bar.png',
    ['icon_size'] = 32,
    ['high_alch'] = 50,
    ['low_alch'] = 33,
    ['examine'] = 'Used in Smithing (20).',
  },
  ['Mithril bar'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'rs-bar',
    ['stack_size'] = 100,
    ['order'] = 30,
    ['rs_name'] = 'mithril_bar',
    ['name'] = 'rs-mithril-bar',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsSmithing__/graphics/icons/auto_generated/mithril_bar.png',
    ['icon_size'] = 32,
    ['high_alch'] = 75,
    ['low_alch'] = 50,
    ['examine'] = 'Used in Smithing (30).',
  },
  ['Adamant bar'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'rs-bar',
    ['stack_size'] = 100,
    ['order'] = 40,
    ['rs_name'] = 'adamant_bar',
    ['name'] = 'rs-adamant-bar',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsSmithing__/graphics/icons/auto_generated/adamant_bar.png',
    ['icon_size'] = 32,
    ['high_alch'] = 100,
    ['low_alch'] = 66,
    ['examine'] = 'Used in Smithing (40).',
  },
  ['Rune bar'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'rs-bar',
    ['stack_size'] = 100,
    ['order'] = 50,
    ['rs_name'] = 'rune_bar',
    ['name'] = 'rs-rune-bar',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsSmithing__/graphics/icons/auto_generated/rune_bar.png',
    ['icon_size'] = 32,
    ['high_alch'] = 250,
    ['low_alch'] = 166,
    ['examine'] = 'Used in Smithing (50).',
  },
  ['Orikalkum bar'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'rs-bar',
    ['stack_size'] = 100,
    ['order'] = 60,
    ['rs_name'] = 'orikalkum_bar',
    ['name'] = 'rs-orikalkum-bar',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsSmithing__/graphics/icons/auto_generated/orikalkum_bar.png',
    ['icon_size'] = 32,
    ['high_alch'] = 500,
    ['low_alch'] = 333,
    ['examine'] = 'Used in Smithing (60).',
  },
  ['Necronium bar'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'rs-bar',
    ['stack_size'] = 100,
    ['order'] = 70,
    ['rs_name'] = 'necronium_bar',
    ['name'] = 'rs-necronium-bar',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsSmithing__/graphics/icons/auto_generated/necronium_bar.png',
    ['icon_size'] = 32,
    ['high_alch'] = 1000,
    ['low_alch'] = 666,
    ['examine'] = 'Used in Smithing (70).',
  },
  ['Bane bar'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'rs-bar',
    ['stack_size'] = 100,
    ['order'] = 80,
    ['rs_name'] = 'bane_bar',
    ['name'] = 'rs-bane-bar',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsSmithing__/graphics/icons/auto_generated/bane_bar.png',
    ['icon_size'] = 32,
    ['high_alch'] = 2000,
    ['low_alch'] = 1333,
    ['examine'] = 'Used in Smithing (80).',
  },
  ['Elder rune bar'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'rs-bar',
    ['stack_size'] = 100,
    ['order'] = 90,
    ['rs_name'] = 'elder_rune_bar',
    ['name'] = 'rs-elder-rune-bar',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsSmithing__/graphics/icons/auto_generated/elder_rune_bar.png',
    ['icon_size'] = 32,
    ['high_alch'] = 5000,
    ['low_alch'] = 3333,
    ['examine'] = 'Used in Smithing (90).',
  },
  ['Bronze nails'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'rs-smithing-intermediate',
    ['stack_size'] = 2000,
    ['order'] = 'nails-1',
    ['rs_name'] = 'bronze_nails',
    ['name'] = 'rs-bronze-nails',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsSmithing__/graphics/icons/auto_generated/bronze_nails.png',
    ['icon_size'] = 32,
    ['high_alch'] = 1,
    ['low_alch'] = 0,
    ['examine'] = 'Keeps things in place fairly permanently.',
  },
  ['Iron nails'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'rs-smithing-intermediate',
    ['stack_size'] = 2000,
    ['order'] = 'nails-10',
    ['rs_name'] = 'iron_nails',
    ['name'] = 'rs-iron-nails',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsSmithing__/graphics/icons/auto_generated/iron_nails.png',
    ['icon_size'] = 32,
    ['high_alch'] = 1,
    ['low_alch'] = 0,
    ['examine'] = 'Keeps things in place fairly permanently.',
  },
  ['Steel nails'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'rs-smithing-intermediate',
    ['stack_size'] = 2000,
    ['order'] = 'nails-20',
    ['rs_name'] = 'steel_nails',
    ['name'] = 'rs-steel-nails',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsSmithing__/graphics/icons/auto_generated/steel_nails.png',
    ['icon_size'] = 32,
    ['high_alch'] = 1,
    ['low_alch'] = 1,
    ['examine'] = 'Keeps things in place fairly permanently. Used in Construction (1).',
  },
  ['Mithril nails'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'rs-smithing-intermediate',
    ['stack_size'] = 2000,
    ['order'] = 'nails-30',
    ['rs_name'] = 'mithril_nails',
    ['name'] = 'rs-mithril-nails',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsSmithing__/graphics/icons/auto_generated/mithril_nails.png',
    ['icon_size'] = 32,
    ['high_alch'] = 2,
    ['low_alch'] = 1,
    ['examine'] = 'Keeps things in place fairly permanently.',
  },
  ['Adamant nails'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'rs-smithing-intermediate',
    ['stack_size'] = 2000,
    ['order'] = 'nails-40',
    ['rs_name'] = 'adamant_nails',
    ['name'] = 'rs-adamant-nails',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsSmithing__/graphics/icons/auto_generated/adamant_nails.png',
    ['icon_size'] = 32,
    ['high_alch'] = 3,
    ['low_alch'] = 2,
    ['examine'] = 'Keeps things in place fairly permanently.',
  },
  ['Rune nails'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'rs-smithing-intermediate',
    ['stack_size'] = 2000,
    ['order'] = 'nails-50',
    ['rs_name'] = 'rune_nails',
    ['name'] = 'rs-rune-nails',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsSmithing__/graphics/icons/auto_generated/rune_nails.png',
    ['icon_size'] = 32,
    ['high_alch'] = 6,
    ['low_alch'] = 4,
    ['examine'] = 'Keeps things in place fairly permanently.',
  },
  ['Bronze pickaxe'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'rs-pickaxe',
    ['stack_size'] = 50,
    ['order'] = 1,
    ['rs_name'] = 'bronze_pickaxe',
    ['name'] = 'rs-bronze-pickaxe',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsSmithing__/graphics/icons/auto_generated/bronze_pickaxe.png',
    ['icon_size'] = 32,
    ['high_alch'] = 100,
    ['low_alch'] = 67,
    ['examine'] = 'Used for mining.',
  },
  ['Iron pickaxe'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'rs-pickaxe',
    ['stack_size'] = 50,
    ['order'] = 10,
    ['rs_name'] = 'iron_pickaxe',
    ['name'] = 'rs-iron-pickaxe',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsSmithing__/graphics/icons/auto_generated/iron_pickaxe.png',
    ['icon_size'] = 32,
    ['high_alch'] = 150,
    ['low_alch'] = 100,
    ['examine'] = 'Used for mining.',
  },
  ['Steel pickaxe'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'rs-pickaxe',
    ['stack_size'] = 50,
    ['order'] = 20,
    ['rs_name'] = 'steel_pickaxe',
    ['name'] = 'rs-steel-pickaxe',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsSmithing__/graphics/icons/auto_generated/steel_pickaxe.png',
    ['icon_size'] = 32,
    ['high_alch'] = 200,
    ['low_alch'] = 133,
    ['examine'] = 'A steel pickaxe.',
  },
  ['Mithril pickaxe'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'rs-pickaxe',
    ['stack_size'] = 50,
    ['order'] = 30,
    ['rs_name'] = 'mithril_pickaxe',
    ['name'] = 'rs-mithril-pickaxe',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsSmithing__/graphics/icons/auto_generated/mithril_pickaxe.png',
    ['icon_size'] = 32,
    ['high_alch'] = 300,
    ['low_alch'] = 200,
    ['examine'] = 'A mithril pickaxe.',
  },
  ['Adamant pickaxe'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'rs-pickaxe',
    ['stack_size'] = 50,
    ['order'] = 40,
    ['rs_name'] = 'adamant_pickaxe',
    ['name'] = 'rs-adamant-pickaxe',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsSmithing__/graphics/icons/auto_generated/adamant_pickaxe.png',
    ['icon_size'] = 32,
    ['high_alch'] = 400,
    ['low_alch'] = 267,
    ['examine'] = 'An adamant pickaxe.',
  },
  ['Rune pickaxe'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'rs-pickaxe',
    ['stack_size'] = 50,
    ['order'] = 50,
    ['rs_name'] = 'rune_pickaxe',
    ['name'] = 'rs-rune-pickaxe',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsSmithing__/graphics/icons/auto_generated/rune_pickaxe.png',
    ['icon_size'] = 32,
    ['high_alch'] = 1000,
    ['low_alch'] = 667,
    ['examine'] = 'A rune pickaxe.',
  },
  ['Orikalkum pickaxe'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'rs-pickaxe',
    ['stack_size'] = 50,
    ['order'] = 60,
    ['rs_name'] = 'orikalkum_pickaxe',
    ['name'] = 'rs-orikalkum-pickaxe',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsSmithing__/graphics/icons/auto_generated/orikalkum_pickaxe.png',
    ['icon_size'] = 32,
    ['high_alch'] = 2000,
    ['low_alch'] = 1333,
    ['examine'] = 'An orikalkum pickaxe.',
  },
  ['Necronium pickaxe'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'rs-pickaxe',
    ['stack_size'] = 50,
    ['order'] = 70,
    ['rs_name'] = 'necronium_pickaxe',
    ['name'] = 'rs-necronium-pickaxe',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsSmithing__/graphics/icons/auto_generated/necronium_pickaxe.png',
    ['icon_size'] = 32,
    ['high_alch'] = 4000,
    ['low_alch'] = 2667,
    ['examine'] = 'A necronium pickaxe.',
  },
  ['Bane pickaxe'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'rs-pickaxe',
    ['stack_size'] = 50,
    ['order'] = 80,
    ['rs_name'] = 'bane_pickaxe',
    ['name'] = 'rs-bane-pickaxe',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsSmithing__/graphics/icons/auto_generated/bane_pickaxe.png',
    ['icon_size'] = 32,
    ['high_alch'] = 8000,
    ['low_alch'] = 5333,
    ['examine'] = 'A bane pickaxe.',
  },
  ['Elder rune pickaxe'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'rs-pickaxe',
    ['stack_size'] = 50,
    ['order'] = 90,
    ['rs_name'] = 'elder_rune_pickaxe',
    ['name'] = 'rs-elder-rune-pickaxe',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsSmithing__/graphics/icons/auto_generated/elder_rune_pickaxe.png',
    ['icon_size'] = 32,
    ['high_alch'] = 20000,
    ['low_alch'] = 13333,
    ['examine'] = 'An elder rune pickaxe.',
  },
}