return {
  ['Clay'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'rs-clay',
    ['stack_size'] = 50,
    ['order'] = '001-clay',
    ['vanilla_name'] = 'stone',
    ['rs_name'] = 'clay',
    ['name'] = 'rs-clay',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/auto_generated/clay.png',
    ['icon_size'] = 32,
    ['high_alch'] = 0,
    ['low_alch'] = 0,
    ['examine'] = 'Some hard dry clay.',
    ['pictures'] = 'nil',
    ['icon_mipmaps'] = 'nil',
  },
  ['Tin ore'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'rs-ore',
    ['stack_size'] = 50,
    ['order'] = '02',
    ['rs_name'] = 'tin_ore',
    ['name'] = 'rs-tin-ore',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/auto_generated/tin_ore.png',
    ['icon_size'] = 32,
    ['high_alch'] = 10,
    ['low_alch'] = 6,
    ['examine'] = 'Used in Smithing (1).',
  },
  ['Copper ore'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'rs-ore',
    ['stack_size'] = 50,
    ['order'] = '02',
    ['vanilla_name'] = 'copper-ore',
    ['rs_name'] = 'copper_ore',
    ['name'] = 'rs-copper-ore',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/auto_generated/copper_ore.png',
    ['icon_size'] = 32,
    ['high_alch'] = 10,
    ['low_alch'] = 6,
    ['examine'] = 'Used in Smithing (1).',
    ['pictures'] = 'nil',
    ['icon_mipmaps'] = 'nil',
  },
  ['Iron ore'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'rs-ore',
    ['stack_size'] = 50,
    ['order'] = 10,
    ['vanilla_name'] = 'iron-ore',
    ['rs_name'] = 'iron_ore',
    ['name'] = 'rs-iron-ore',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/auto_generated/iron_ore.png',
    ['icon_size'] = 32,
    ['high_alch'] = 15,
    ['low_alch'] = 10,
    ['examine'] = 'Used in Smithing (10,20).',
    ['pictures'] = 'nil',
    ['icon_mipmaps'] = 'nil',
  },
  ['Coal'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'rs-ore',
    ['stack_size'] = 50,
    ['order'] = 19,
    ['fuel_category'] = 'chemical',
    ['fuel_value'] = '4MJ',
    ['vanilla_name'] = 'coal',
    ['rs_name'] = 'coal',
    ['name'] = 'rs-coal',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/auto_generated/coal.png',
    ['icon_size'] = 32,
    ['high_alch'] = 25,
    ['low_alch'] = 16,
    ['examine'] = 'Used in Smithing (20,30).',
    ['pictures'] = 'nil',
    ['icon_mipmaps'] = 'nil',
    ['dark_background_icon'] = 'nil',
  },
  ['Mithril ore'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'rs-ore',
    ['stack_size'] = 50,
    ['order'] = 30,
    ['rs_name'] = 'mithril_ore',
    ['name'] = 'rs-mithril-ore',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/auto_generated/mithril_ore.png',
    ['icon_size'] = 32,
    ['high_alch'] = 35,
    ['low_alch'] = 23,
    ['examine'] = 'Used in Smithing (30).',
  },
  ['Luminite'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'rs-ore',
    ['stack_size'] = 50,
    ['order'] = 39,
    ['fuel_category'] = 'chemical',
    ['fuel_value'] = '12MJ',
    ['rs_name'] = 'luminite',
    ['name'] = 'rs-luminite',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/auto_generated/luminite.png',
    ['icon_size'] = 32,
    ['high_alch'] = 50,
    ['low_alch'] = 33,
    ['examine'] = 'Used in Smithing (40,50).',
  },
  ['Adamantite ore'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'rs-ore',
    ['stack_size'] = 50,
    ['order'] = 40,
    ['rs_name'] = 'adamantite_ore',
    ['name'] = 'rs-adamantite-ore',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/auto_generated/adamantite_ore.png',
    ['icon_size'] = 32,
    ['high_alch'] = 50,
    ['low_alch'] = 33,
    ['examine'] = 'Used in Smithing (40).',
  },
  ['Runite ore'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'rs-ore',
    ['stack_size'] = 50,
    ['order'] = 50,
    ['rs_name'] = 'runite_ore',
    ['name'] = 'rs-runite-ore',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/auto_generated/runite_ore.png',
    ['icon_size'] = 32,
    ['high_alch'] = 125,
    ['low_alch'] = 83,
    ['examine'] = 'Used in Smithing (50).',
  },
  ['Drakolith'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'rs-ore',
    ['stack_size'] = 50,
    ['order'] = 59,
    ['fuel_category'] = 'chemical',
    ['fuel_value'] = '24MJ',
    ['rs_name'] = 'drakolith',
    ['name'] = 'rs-drakolith',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/auto_generated/drakolith.png',
    ['icon_size'] = 32,
    ['high_alch'] = 250,
    ['low_alch'] = 166,
    ['examine'] = 'Used in Smithing (60).',
  },
  ['Orichalcite ore'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'rs-ore',
    ['stack_size'] = 50,
    ['order'] = 60,
    ['rs_name'] = 'orichalcite_ore',
    ['name'] = 'rs-orichalcite-ore',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/auto_generated/orichalcite_ore.png',
    ['icon_size'] = 32,
    ['high_alch'] = 250,
    ['low_alch'] = 166,
    ['examine'] = 'Used in Smithing (60).',
  },
  ['Phasmatite'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'rs-ore',
    ['stack_size'] = 50,
    ['order'] = 69,
    ['vanilla_name'] = 'uranium-ore',
    ['rs_name'] = 'phasmatite',
    ['name'] = 'rs-phasmatite',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/auto_generated/phasmatite.png',
    ['icon_size'] = 32,
    ['high_alch'] = 500,
    ['low_alch'] = 333,
    ['examine'] = 'Used in Smithing (70).',
    ['pictures'] = 'nil',
    ['icon_mipmaps'] = 'nil',
  },
  ['Necrite ore'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'rs-ore',
    ['stack_size'] = 50,
    ['order'] = 70,
    ['rs_name'] = 'necrite_ore',
    ['name'] = 'rs-necrite-ore',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/auto_generated/necrite_ore.png',
    ['icon_size'] = 32,
    ['high_alch'] = 500,
    ['low_alch'] = 333,
    ['examine'] = 'Used in Smithing (70).',
  },
  ['Banite ore'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'rs-ore',
    ['stack_size'] = 50,
    ['order'] = 80,
    ['rs_name'] = 'banite_ore',
    ['name'] = 'rs-banite-ore',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/auto_generated/banite_ore.png',
    ['icon_size'] = 32,
    ['high_alch'] = 640,
    ['low_alch'] = 426,
    ['examine'] = 'This mystical ore could do with some magical input.',
  },
  ['Light animica'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'rs-ore',
    ['stack_size'] = 50,
    ['order'] = 90,
    ['rs_name'] = 'light_animica',
    ['name'] = 'rs-light-animica',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/auto_generated/light_animica.png',
    ['icon_size'] = 32,
    ['high_alch'] = 1040,
    ['low_alch'] = 693,
    ['examine'] = 'Used in Smithing (90).',
  },
  ['Dark animica'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'rs-ore',
    ['stack_size'] = 50,
    ['order'] = 90,
    ['rs_name'] = 'dark_animica',
    ['name'] = 'rs-dark-animica',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/auto_generated/dark_animica.png',
    ['icon_size'] = 32,
    ['high_alch'] = 1040,
    ['low_alch'] = 693,
    ['examine'] = 'Used in Smithing (90).',
  },
  ['Soft clay'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'rs-clay',
    ['stack_size'] = 100,
    ['order'] = '002-soft',
    ['rs_name'] = 'soft_clay',
    ['name'] = 'rs-soft-clay',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/auto_generated/soft_clay.png',
    ['icon_size'] = 32,
    ['high_alch'] = 1,
    ['low_alch'] = 0,
    ['examine'] = 'Clay soft enough to mould. Used in Crafting (1).',
  },
}