return {
  ['Clay'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'ore',
    ['stack_size'] = 50,
    ['order'] = '01',
    ['vanilla_name'] = 'stone',
    ['rs_name'] = 'clay',
    ['name'] = 'rs-clay',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/clay.png',
    ['icon_size'] = 32,
    ['localised_name'] = {
      'item-name.rs-clay',
    },
    ['localised_description'] = {
      'item-description.rs-clay',
    },
    ['high_alch'] = 0,
    ['low_alch'] = 0,
    ['examine'] = 'Some hard dry clay.',
    ['pictures'] = 'nil',
    ['icon_mipmaps'] = 'nil',
  },
  ['Tin ore'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'ore',
    ['stack_size'] = 50,
    ['order'] = '02',
    ['rs_name'] = 'tin_ore',
    ['name'] = 'rs-tin-ore',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/tin_ore.png',
    ['icon_size'] = 32,
    ['localised_name'] = {
      'item-name.rs-tin-ore',
    },
    ['localised_description'] = {
      'item-description.rs-tin-ore',
    },
    ['high_alch'] = 10,
    ['low_alch'] = 6,
    ['examine'] = 'Used in Smithing (1).',
  },
  ['Copper ore'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'ore',
    ['stack_size'] = 50,
    ['order'] = '02',
    ['vanilla_name'] = 'copper-ore',
    ['rs_name'] = 'copper_ore',
    ['name'] = 'rs-copper-ore',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/copper_ore.png',
    ['icon_size'] = 32,
    ['localised_name'] = {
      'item-name.rs-copper-ore',
    },
    ['localised_description'] = {
      'item-description.rs-copper-ore',
    },
    ['high_alch'] = 10,
    ['low_alch'] = 6,
    ['examine'] = 'Used in Smithing (1).',
    ['pictures'] = 'nil',
    ['icon_mipmaps'] = 'nil',
  },
  ['Iron ore'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'ore',
    ['stack_size'] = 50,
    ['order'] = 10,
    ['vanilla_name'] = 'iron-ore',
    ['rs_name'] = 'iron_ore',
    ['name'] = 'rs-iron-ore',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/iron_ore.png',
    ['icon_size'] = 32,
    ['localised_name'] = {
      'item-name.rs-iron-ore',
    },
    ['localised_description'] = {
      'item-description.rs-iron-ore',
    },
    ['high_alch'] = 15,
    ['low_alch'] = 10,
    ['examine'] = 'Used in Smithing (10,20).',
    ['pictures'] = 'nil',
    ['icon_mipmaps'] = 'nil',
  },
  ['Coal'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'ore',
    ['stack_size'] = 50,
    ['order'] = 19,
    ['fuel_category'] = 'chemical',
    ['fuel_value'] = '4MJ',
    ['vanilla_name'] = 'coal',
    ['rs_name'] = 'coal',
    ['name'] = 'rs-coal',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/coal.png',
    ['icon_size'] = 32,
    ['localised_name'] = {
      'item-name.rs-coal',
    },
    ['localised_description'] = {
      'item-description.rs-coal',
    },
    ['high_alch'] = 25,
    ['low_alch'] = 16,
    ['examine'] = 'Used in Smithing (20,30).',
    ['pictures'] = 'nil',
    ['icon_mipmaps'] = 'nil',
    ['dark_background_icon'] = 'nil',
  },
  ['Mithril ore'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'ore',
    ['stack_size'] = 50,
    ['order'] = 30,
    ['rs_name'] = 'mithril_ore',
    ['name'] = 'rs-mithril-ore',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/mithril_ore.png',
    ['icon_size'] = 32,
    ['localised_name'] = {
      'item-name.rs-mithril-ore',
    },
    ['localised_description'] = {
      'item-description.rs-mithril-ore',
    },
    ['high_alch'] = 35,
    ['low_alch'] = 23,
    ['examine'] = 'Used in Smithing (30).',
  },
  ['Luminite'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'ore',
    ['stack_size'] = 50,
    ['order'] = 39,
    ['fuel_category'] = 'chemical',
    ['fuel_value'] = '12MJ',
    ['rs_name'] = 'luminite',
    ['name'] = 'rs-luminite',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/luminite.png',
    ['icon_size'] = 32,
    ['localised_name'] = {
      'item-name.rs-luminite',
    },
    ['localised_description'] = {
      'item-description.rs-luminite',
    },
    ['high_alch'] = 50,
    ['low_alch'] = 33,
    ['examine'] = 'Used in Smithing (40,50).',
  },
  ['Adamantite ore'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'ore',
    ['stack_size'] = 50,
    ['order'] = 40,
    ['rs_name'] = 'adamantite_ore',
    ['name'] = 'rs-adamantite-ore',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/adamantite_ore.png',
    ['icon_size'] = 32,
    ['localised_name'] = {
      'item-name.rs-adamantite-ore',
    },
    ['localised_description'] = {
      'item-description.rs-adamantite-ore',
    },
    ['high_alch'] = 50,
    ['low_alch'] = 33,
    ['examine'] = 'Used in Smithing (40).',
  },
  ['Runite ore'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'ore',
    ['stack_size'] = 50,
    ['order'] = 50,
    ['rs_name'] = 'runite_ore',
    ['name'] = 'rs-runite-ore',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/runite_ore.png',
    ['icon_size'] = 32,
    ['localised_name'] = {
      'item-name.rs-runite-ore',
    },
    ['localised_description'] = {
      'item-description.rs-runite-ore',
    },
    ['high_alch'] = 125,
    ['low_alch'] = 83,
    ['examine'] = 'Used in Smithing (50).',
  },
  ['Drakolith'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'ore',
    ['stack_size'] = 50,
    ['order'] = 59,
    ['fuel_category'] = 'chemical',
    ['fuel_value'] = '24MJ',
    ['rs_name'] = 'drakolith',
    ['name'] = 'rs-drakolith',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/drakolith.png',
    ['icon_size'] = 32,
    ['localised_name'] = {
      'item-name.rs-drakolith',
    },
    ['localised_description'] = {
      'item-description.rs-drakolith',
    },
    ['high_alch'] = 250,
    ['low_alch'] = 166,
    ['examine'] = 'Used in Smithing (60).',
  },
  ['Orichalcite ore'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'ore',
    ['stack_size'] = 50,
    ['order'] = 60,
    ['rs_name'] = 'orichalcite_ore',
    ['name'] = 'rs-orichalcite-ore',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/orichalcite_ore.png',
    ['icon_size'] = 32,
    ['localised_name'] = {
      'item-name.rs-orichalcite-ore',
    },
    ['localised_description'] = {
      'item-description.rs-orichalcite-ore',
    },
    ['high_alch'] = 250,
    ['low_alch'] = 166,
    ['examine'] = 'Used in Smithing (60).',
  },
  ['Phasmatite'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'ore',
    ['stack_size'] = 50,
    ['order'] = 69,
    ['vanilla_name'] = 'uranium-ore',
    ['rs_name'] = 'phasmatite',
    ['name'] = 'rs-phasmatite',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/phasmatite.png',
    ['icon_size'] = 32,
    ['localised_name'] = {
      'item-name.rs-phasmatite',
    },
    ['localised_description'] = {
      'item-description.rs-phasmatite',
    },
    ['high_alch'] = 500,
    ['low_alch'] = 333,
    ['examine'] = 'Used in Smithing (70).',
  },
  ['Necrite ore'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'ore',
    ['stack_size'] = 50,
    ['order'] = 70,
    ['rs_name'] = 'necrite_ore',
    ['name'] = 'rs-necrite-ore',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/necrite_ore.png',
    ['icon_size'] = 32,
    ['localised_name'] = {
      'item-name.rs-necrite-ore',
    },
    ['localised_description'] = {
      'item-description.rs-necrite-ore',
    },
    ['high_alch'] = 500,
    ['low_alch'] = 333,
    ['examine'] = 'Used in Smithing (70).',
  },
  ['Banite ore'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'ore',
    ['stack_size'] = 50,
    ['order'] = 80,
    ['rs_name'] = 'banite_ore',
    ['name'] = 'rs-banite-ore',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/banite_ore.png',
    ['icon_size'] = 32,
    ['localised_name'] = {
      'item-name.rs-banite-ore',
    },
    ['localised_description'] = {
      'item-description.rs-banite-ore',
    },
    ['high_alch'] = 640,
    ['low_alch'] = 426,
    ['examine'] = 'This mystical ore could do with some magical input.',
  },
  ['Light animica'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'ore',
    ['stack_size'] = 50,
    ['order'] = 90,
    ['rs_name'] = 'light_animica',
    ['name'] = 'rs-light-animica',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/light_animica.png',
    ['icon_size'] = 32,
    ['localised_name'] = {
      'item-name.rs-light-animica',
    },
    ['localised_description'] = {
      'item-description.rs-light-animica',
    },
    ['high_alch'] = 1040,
    ['low_alch'] = 693,
    ['examine'] = 'Used in Smithing (90).',
  },
  ['Dark animica'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'ore',
    ['stack_size'] = 50,
    ['order'] = 90,
    ['rs_name'] = 'dark_animica',
    ['name'] = 'rs-dark-animica',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/dark_animica.png',
    ['icon_size'] = 32,
    ['localised_name'] = {
      'item-name.rs-dark-animica',
    },
    ['localised_description'] = {
      'item-description.rs-dark-animica',
    },
    ['high_alch'] = 1040,
    ['low_alch'] = 693,
    ['examine'] = 'Used in Smithing (90).',
  },
  ['Soft clay'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'intermediate',
    ['stack_size'] = 100,
    ['order'] = 1,
    ['rs_name'] = 'soft_clay',
    ['name'] = 'rs-soft-clay',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/soft_clay.png',
    ['icon_size'] = 32,
    ['localised_name'] = {
      'item-name.rs-soft-clay',
    },
    ['localised_description'] = {
      'item-description.rs-soft-clay',
    },
    ['high_alch'] = 1,
    ['low_alch'] = 0,
    ['examine'] = 'Clay soft enough to mould. Used in Crafting (1).',
  },
  ['Bronze bar'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'bar',
    ['stack_size'] = 100,
    ['order'] = 1,
    ['vanilla_name'] = 'copper-plate',
    ['rs_name'] = 'bronze_bar',
    ['name'] = 'rs-bronze-bar',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/bronze_bar.png',
    ['icon_size'] = 32,
    ['localised_name'] = {
      'item-name.rs-bronze-bar',
    },
    ['localised_description'] = {
      'item-description.rs-bronze-bar',
    },
    ['high_alch'] = 27,
    ['low_alch'] = 18,
    ['examine'] = 'Used in Smithing (1).',
  },
  ['Iron bar'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'bar',
    ['stack_size'] = 100,
    ['order'] = 10,
    ['vanilla_name'] = 'iron-plate',
    ['rs_name'] = 'iron_bar',
    ['name'] = 'rs-iron-bar',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/iron_bar.png',
    ['icon_size'] = 32,
    ['localised_name'] = {
      'item-name.rs-iron-bar',
    },
    ['localised_description'] = {
      'item-description.rs-iron-bar',
    },
    ['high_alch'] = 35,
    ['low_alch'] = 23,
    ['examine'] = 'Used in Smithing (10).',
  },
  ['Steel bar'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'bar',
    ['stack_size'] = 100,
    ['order'] = 20,
    ['vanilla_name'] = 'steel-plate',
    ['rs_name'] = 'steel_bar',
    ['name'] = 'rs-steel-bar',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/steel_bar.png',
    ['icon_size'] = 32,
    ['localised_name'] = {
      'item-name.rs-steel-bar',
    },
    ['localised_description'] = {
      'item-description.rs-steel-bar',
    },
    ['high_alch'] = 50,
    ['low_alch'] = 33,
    ['examine'] = 'Used in Smithing (20).',
  },
  ['Mithril bar'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'bar',
    ['stack_size'] = 100,
    ['order'] = 30,
    ['rs_name'] = 'mithril_bar',
    ['name'] = 'rs-mithril-bar',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/mithril_bar.png',
    ['icon_size'] = 32,
    ['localised_name'] = {
      'item-name.rs-mithril-bar',
    },
    ['localised_description'] = {
      'item-description.rs-mithril-bar',
    },
    ['high_alch'] = 75,
    ['low_alch'] = 50,
    ['examine'] = 'Used in Smithing (30).',
  },
  ['Adamant bar'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'bar',
    ['stack_size'] = 100,
    ['order'] = 40,
    ['rs_name'] = 'adamant_bar',
    ['name'] = 'rs-adamant-bar',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/adamant_bar.png',
    ['icon_size'] = 32,
    ['localised_name'] = {
      'item-name.rs-adamant-bar',
    },
    ['localised_description'] = {
      'item-description.rs-adamant-bar',
    },
    ['high_alch'] = 100,
    ['low_alch'] = 66,
    ['examine'] = 'Used in Smithing (40).',
  },
  ['Rune bar'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'bar',
    ['stack_size'] = 100,
    ['order'] = 50,
    ['rs_name'] = 'rune_bar',
    ['name'] = 'rs-rune-bar',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/rune_bar.png',
    ['icon_size'] = 32,
    ['localised_name'] = {
      'item-name.rs-rune-bar',
    },
    ['localised_description'] = {
      'item-description.rs-rune-bar',
    },
    ['high_alch'] = 250,
    ['low_alch'] = 166,
    ['examine'] = 'Used in Smithing (50).',
  },
  ['Orikalkum bar'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'bar',
    ['stack_size'] = 100,
    ['order'] = 60,
    ['rs_name'] = 'orikalkum_bar',
    ['name'] = 'rs-orikalkum-bar',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/orikalkum_bar.png',
    ['icon_size'] = 32,
    ['localised_name'] = {
      'item-name.rs-orikalkum-bar',
    },
    ['localised_description'] = {
      'item-description.rs-orikalkum-bar',
    },
    ['high_alch'] = 500,
    ['low_alch'] = 333,
    ['examine'] = 'Used in Smithing (60).',
  },
  ['Necronium bar'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'bar',
    ['stack_size'] = 100,
    ['order'] = 70,
    ['rs_name'] = 'necronium_bar',
    ['name'] = 'rs-necronium-bar',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/necronium_bar.png',
    ['icon_size'] = 32,
    ['localised_name'] = {
      'item-name.rs-necronium-bar',
    },
    ['localised_description'] = {
      'item-description.rs-necronium-bar',
    },
    ['high_alch'] = 1000,
    ['low_alch'] = 666,
    ['examine'] = 'Used in Smithing (70).',
  },
  ['Bane bar'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'bar',
    ['stack_size'] = 100,
    ['order'] = 80,
    ['rs_name'] = 'bane_bar',
    ['name'] = 'rs-bane-bar',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/bane_bar.png',
    ['icon_size'] = 32,
    ['localised_name'] = {
      'item-name.rs-bane-bar',
    },
    ['localised_description'] = {
      'item-description.rs-bane-bar',
    },
    ['high_alch'] = 2000,
    ['low_alch'] = 1333,
    ['examine'] = 'Used in Smithing (80).',
  },
  ['Elder rune bar'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'bar',
    ['stack_size'] = 100,
    ['order'] = 90,
    ['rs_name'] = 'elder_rune_bar',
    ['name'] = 'rs-elder-rune-bar',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/elder_rune_bar.png',
    ['icon_size'] = 32,
    ['localised_name'] = {
      'item-name.rs-elder-rune-bar',
    },
    ['localised_description'] = {
      'item-description.rs-elder-rune-bar',
    },
    ['high_alch'] = 5000,
    ['low_alch'] = 3333,
    ['examine'] = 'Used in Smithing (90).',
  },
  ['Bronze nails'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'intermediate',
    ['stack_size'] = 2000,
    ['order'] = 'nails-1',
    ['rs_name'] = 'bronze_nails',
    ['name'] = 'rs-bronze-nails',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/bronze_nails.png',
    ['icon_size'] = 32,
    ['localised_name'] = {
      'item-name.rs-bronze-nails',
    },
    ['localised_description'] = {
      'item-description.rs-bronze-nails',
    },
    ['high_alch'] = 1,
    ['low_alch'] = 0,
    ['examine'] = 'Keeps things in place fairly permanently.',
  },
  ['Iron nails'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'intermediate',
    ['stack_size'] = 2000,
    ['order'] = 'nails-10',
    ['rs_name'] = 'iron_nails',
    ['name'] = 'rs-iron-nails',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/iron_nails.png',
    ['icon_size'] = 32,
    ['localised_name'] = {
      'item-name.rs-iron-nails',
    },
    ['localised_description'] = {
      'item-description.rs-iron-nails',
    },
    ['high_alch'] = 1,
    ['low_alch'] = 0,
    ['examine'] = 'Keeps things in place fairly permanently.',
  },
  ['Steel nails'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'intermediate',
    ['stack_size'] = 2000,
    ['order'] = 'nails-20',
    ['rs_name'] = 'steel_nails',
    ['name'] = 'rs-steel-nails',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/steel_nails.png',
    ['icon_size'] = 32,
    ['localised_name'] = {
      'item-name.rs-steel-nails',
    },
    ['localised_description'] = {
      'item-description.rs-steel-nails',
    },
    ['high_alch'] = 1,
    ['low_alch'] = 1,
    ['examine'] = 'Keeps things in place fairly permanently. Used in Construction (1).',
  },
  ['Mithril nails'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'intermediate',
    ['stack_size'] = 2000,
    ['order'] = 'nails-30',
    ['rs_name'] = 'mithril_nails',
    ['name'] = 'rs-mithril-nails',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/mithril_nails.png',
    ['icon_size'] = 32,
    ['localised_name'] = {
      'item-name.rs-mithril-nails',
    },
    ['localised_description'] = {
      'item-description.rs-mithril-nails',
    },
    ['high_alch'] = 2,
    ['low_alch'] = 1,
    ['examine'] = 'Keeps things in place fairly permanently.',
  },
  ['Adamant nails'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'intermediate',
    ['stack_size'] = 2000,
    ['order'] = 'nails-40',
    ['rs_name'] = 'adamant_nails',
    ['name'] = 'rs-adamant-nails',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/adamant_nails.png',
    ['icon_size'] = 32,
    ['localised_name'] = {
      'item-name.rs-adamant-nails',
    },
    ['localised_description'] = {
      'item-description.rs-adamant-nails',
    },
    ['high_alch'] = 3,
    ['low_alch'] = 2,
    ['examine'] = 'Keeps things in place fairly permanently.',
  },
  ['Rune nails'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'intermediate',
    ['stack_size'] = 2000,
    ['order'] = 'nails-50',
    ['rs_name'] = 'rune_nails',
    ['name'] = 'rs-rune-nails',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/rune_nails.png',
    ['icon_size'] = 32,
    ['localised_name'] = {
      'item-name.rs-rune-nails',
    },
    ['localised_description'] = {
      'item-description.rs-rune-nails',
    },
    ['high_alch'] = 6,
    ['low_alch'] = 4,
    ['examine'] = 'Keeps things in place fairly permanently.',
  },
  ['Bronze pickaxe'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'pickaxe',
    ['stack_size'] = 50,
    ['order'] = 1,
    ['rs_name'] = 'bronze_pickaxe',
    ['name'] = 'rs-bronze-pickaxe',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/bronze_pickaxe.png',
    ['icon_size'] = 32,
    ['localised_name'] = {
      'item-name.rs-bronze-pickaxe',
    },
    ['localised_description'] = {
      'item-description.rs-bronze-pickaxe',
    },
    ['high_alch'] = 100,
    ['low_alch'] = 67,
    ['examine'] = 'Used for mining.',
  },
  ['Iron pickaxe'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'pickaxe',
    ['stack_size'] = 50,
    ['order'] = 10,
    ['rs_name'] = 'iron_pickaxe',
    ['name'] = 'rs-iron-pickaxe',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/iron_pickaxe.png',
    ['icon_size'] = 32,
    ['localised_name'] = {
      'item-name.rs-iron-pickaxe',
    },
    ['localised_description'] = {
      'item-description.rs-iron-pickaxe',
    },
    ['high_alch'] = 150,
    ['low_alch'] = 100,
    ['examine'] = 'Used for mining.',
  },
  ['Steel pickaxe'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'pickaxe',
    ['stack_size'] = 50,
    ['order'] = 20,
    ['rs_name'] = 'steel_pickaxe',
    ['name'] = 'rs-steel-pickaxe',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/steel_pickaxe.png',
    ['icon_size'] = 32,
    ['localised_name'] = {
      'item-name.rs-steel-pickaxe',
    },
    ['localised_description'] = {
      'item-description.rs-steel-pickaxe',
    },
    ['high_alch'] = 200,
    ['low_alch'] = 133,
    ['examine'] = 'A steel pickaxe.',
  },
  ['Mithril pickaxe'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'pickaxe',
    ['stack_size'] = 50,
    ['order'] = 30,
    ['rs_name'] = 'mithril_pickaxe',
    ['name'] = 'rs-mithril-pickaxe',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/mithril_pickaxe.png',
    ['icon_size'] = 32,
    ['localised_name'] = {
      'item-name.rs-mithril-pickaxe',
    },
    ['localised_description'] = {
      'item-description.rs-mithril-pickaxe',
    },
    ['high_alch'] = 300,
    ['low_alch'] = 200,
    ['examine'] = 'A mithril pickaxe.',
  },
  ['Adamant pickaxe'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'pickaxe',
    ['stack_size'] = 50,
    ['order'] = 40,
    ['rs_name'] = 'adamant_pickaxe',
    ['name'] = 'rs-adamant-pickaxe',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/adamant_pickaxe.png',
    ['icon_size'] = 32,
    ['localised_name'] = {
      'item-name.rs-adamant-pickaxe',
    },
    ['localised_description'] = {
      'item-description.rs-adamant-pickaxe',
    },
    ['high_alch'] = 400,
    ['low_alch'] = 267,
    ['examine'] = 'An adamant pickaxe.',
  },
  ['Rune pickaxe'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'pickaxe',
    ['stack_size'] = 50,
    ['order'] = 50,
    ['rs_name'] = 'rune_pickaxe',
    ['name'] = 'rs-rune-pickaxe',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/rune_pickaxe.png',
    ['icon_size'] = 32,
    ['localised_name'] = {
      'item-name.rs-rune-pickaxe',
    },
    ['localised_description'] = {
      'item-description.rs-rune-pickaxe',
    },
    ['high_alch'] = 1000,
    ['low_alch'] = 667,
    ['examine'] = 'A rune pickaxe.',
  },
  ['Orikalkum pickaxe'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'pickaxe',
    ['stack_size'] = 50,
    ['order'] = 60,
    ['rs_name'] = 'orikalkum_pickaxe',
    ['name'] = 'rs-orikalkum-pickaxe',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/orikalkum_pickaxe.png',
    ['icon_size'] = 32,
    ['localised_name'] = {
      'item-name.rs-orikalkum-pickaxe',
    },
    ['localised_description'] = {
      'item-description.rs-orikalkum-pickaxe',
    },
    ['high_alch'] = 2000,
    ['low_alch'] = 1333,
    ['examine'] = 'An orikalkum pickaxe.',
  },
  ['Necronium pickaxe'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'pickaxe',
    ['stack_size'] = 50,
    ['order'] = 70,
    ['rs_name'] = 'necronium_pickaxe',
    ['name'] = 'rs-necronium-pickaxe',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/necronium_pickaxe.png',
    ['icon_size'] = 32,
    ['localised_name'] = {
      'item-name.rs-necronium-pickaxe',
    },
    ['localised_description'] = {
      'item-description.rs-necronium-pickaxe',
    },
    ['high_alch'] = 4000,
    ['low_alch'] = 2667,
    ['examine'] = 'A necronium pickaxe.',
  },
  ['Bane pickaxe'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'pickaxe',
    ['stack_size'] = 50,
    ['order'] = 80,
    ['rs_name'] = 'bane_pickaxe',
    ['name'] = 'rs-bane-pickaxe',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/bane_pickaxe.png',
    ['icon_size'] = 32,
    ['localised_name'] = {
      'item-name.rs-bane-pickaxe',
    },
    ['localised_description'] = {
      'item-description.rs-bane-pickaxe',
    },
    ['high_alch'] = 8000,
    ['low_alch'] = 5333,
    ['examine'] = 'A bane pickaxe.',
  },
  ['Elder rune pickaxe'] = {
    ['group'] = 'mining-and-smithing',
    ['subgroup'] = 'pickaxe',
    ['stack_size'] = 50,
    ['order'] = 90,
    ['rs_name'] = 'elder_rune_pickaxe',
    ['name'] = 'rs-elder-rune-pickaxe',
    ['type'] = 'item',
    ['flags'] = {
    },
    ['icon'] = '__RsMining__/graphics/icons/elder_rune_pickaxe.png',
    ['icon_size'] = 32,
    ['localised_name'] = {
      'item-name.rs-elder-rune-pickaxe',
    },
    ['localised_description'] = {
      'item-description.rs-elder-rune-pickaxe',
    },
    ['high_alch'] = 20000,
    ['low_alch'] = 13333,
    ['examine'] = 'An elder rune pickaxe.',
  },
}