return {
  ["logs"] = {
    ["subgroup"] = "rs-logs",
    ["order"] = "rs-logs-001",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsWoodcutting__/graphics/icons/auto_generated/logs.png",
    ["rs_name"] = "logs",
    ["name"] = "rs-logs",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 2,
    ["low_alch"] = 1,
    ["examine"] = "A number of wooden logs. Used in Firemaking (1), Fletching (1), Construction (1).",
    ["locale_name"] = "Logs",
  },
  ["Oak logs"] = {
    ["subgroup"] = "rs-logs",
    ["order"] = "rs-logs-015",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsWoodcutting__/graphics/icons/auto_generated/oak_logs.png",
    ["rs_name"] = "oak_logs",
    ["name"] = "rs-oak-logs",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 12,
    ["low_alch"] = 8,
    ["examine"] = "Logs cut from an oak tree. Used in Firemaking (15), Fletching (20).",
    ["locale_name"] = "Oak logs",
  },
  ["Willow logs"] = {
    ["subgroup"] = "rs-logs",
    ["order"] = "rs-logs-030",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsWoodcutting__/graphics/icons/auto_generated/willow_logs.png",
    ["rs_name"] = "willow_logs",
    ["name"] = "rs-willow-logs",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 24,
    ["low_alch"] = 16,
    ["examine"] = "Logs cut from a willow tree.",
    ["locale_name"] = "Willow logs",
  },
  ["Maple logs"] = {
    ["subgroup"] = "rs-logs",
    ["order"] = "rs-logs-045",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsWoodcutting__/graphics/icons/auto_generated/maple_logs.png",
    ["rs_name"] = "maple_logs",
    ["name"] = "rs-maple-logs",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 48,
    ["low_alch"] = 32,
    ["examine"] = "Logs cut from a maple tree.",
    ["locale_name"] = "Maple logs",
  },
  ["Yew logs"] = {
    ["subgroup"] = "rs-logs",
    ["order"] = "rs-logs-060",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsWoodcutting__/graphics/icons/auto_generated/yew_logs.png",
    ["rs_name"] = "yew_logs",
    ["name"] = "rs-yew-logs",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 96,
    ["low_alch"] = 64,
    ["examine"] = "Logs cut from a yew tree.",
    ["locale_name"] = "Yew logs",
  },
  ["Magic logs"] = {
    ["subgroup"] = "rs-logs",
    ["order"] = "rs-logs-075",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsWoodcutting__/graphics/icons/auto_generated/magic_logs.png",
    ["rs_name"] = "magic_logs",
    ["name"] = "rs-magic-logs",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 192,
    ["low_alch"] = 128,
    ["examine"] = "Logs cut from a magic tree.",
    ["locale_name"] = "Magic logs",
  },
}