return {
  ["Attack potion"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-001",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/attack_potion.png",
    ["rs_name"] = "attack_potion",
    ["name"] = "rs-attack-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 420,
    ["low_alch"] = 168,
    ["examine"] = "3 doses of attack potion.",
    ["locale_name"] = "Attack potion",
  },
  ["Eye of newt"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-001",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/eye_of_newt.png",
    ["rs_name"] = "eye_of_newt",
    ["name"] = "rs-eye-of-newt",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 1,
    ["low_alch"] = 1,
    ["examine"] = "It seems to be looking at me. Used in Herblore (3).",
    ["locale_name"] = "Eye of newt",
  },
  ["Ranging potion"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-003",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/ranging_potion.png",
    ["rs_name"] = "ranging_potion",
    ["name"] = "rs-ranging-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 420,
    ["low_alch"] = 280,
    ["examine"] = "3 doses of ranging potion.",
    ["locale_name"] = "Ranging potion",
  },
  ["Redberries"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-003",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/redberries.png",
    ["rs_name"] = "redberries",
    ["name"] = "rs-redberries",
    ["type"] = "item",
    ["flags"] = {
    },
    ["examine"] = "Very bright red berries.",
    ["locale_name"] = "Redberries",
  },
  ["Magic potion"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-005",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/magic_potion.png",
    ["rs_name"] = "magic_potion",
    ["name"] = "rs-magic-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 168,
    ["low_alch"] = 224,
    ["examine"] = "3 doses of magic potion.",
    ["locale_name"] = "Magic potion",
  },
  ["Black bead"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-005",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/black_bead.png",
    ["rs_name"] = "black_bead",
    ["name"] = "rs-black-bead",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 2,
    ["low_alch"] = 1,
    ["examine"] = "A small round black bead.",
    ["locale_name"] = "Black bead",
  },
  ["Strength potion"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-007",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/strength_potion.png",
    ["rs_name"] = "strength_potion",
    ["name"] = "rs-strength-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 900,
    ["low_alch"] = 600,
    ["examine"] = "3 doses of strength potion.",
    ["locale_name"] = "Strength potion",
  },
  ["Limpwurt root"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-007",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/limpwurt_root.png",
    ["rs_name"] = "limpwurt_root",
    ["name"] = "rs-limpwurt-root",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 4,
    ["low_alch"] = 2,
    ["examine"] = "The root of a limpwurt plant. Used in Herblore (7).",
    ["locale_name"] = "Limpwurt root",
  },
  ["Defence potion"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-009",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/defence_potion.png",
    ["rs_name"] = "defence_potion",
    ["name"] = "rs-defence-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 396,
    ["low_alch"] = 176,
    ["examine"] = "3 doses of defence potion.",
    ["locale_name"] = "Defence potion",
  },
  ["Bear fur"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-009",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/bear_fur.png",
    ["rs_name"] = "bear_fur",
    ["name"] = "rs-bear-fur",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 6,
    ["low_alch"] = 4,
    ["examine"] = "Warm fur from a bear. Used in Herblore (9).",
    ["locale_name"] = "Bear fur",
  },
  ["Antipoison"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-013",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/antipoison.png",
    ["rs_name"] = "antipoison",
    ["name"] = "rs-antipoison",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 216,
    ["low_alch"] = 57,
    ["examine"] = "3 doses of antipoison potion.",
    ["locale_name"] = "Antipoison",
  },
  ["Unicorn horn dust"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-013",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/unicorn_horn_dust.png",
    ["rs_name"] = "unicorn_horn_dust",
    ["name"] = "rs-unicorn-horn-dust",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 12,
    ["low_alch"] = 8,
    ["examine"] = "Finely ground horn of Unicorn.",
    ["locale_name"] = "Unicorn horn dust",
  },
  ["Serum 207"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-015",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/serum_207.png",
    ["rs_name"] = "serum_207",
    ["name"] = "rs-serum-207",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 7,
    ["low_alch"] = 5,
    ["examine"] = "3 doses serum 207 as described in Herbi Flax's diary.",
    ["locale_name"] = "Serum 207",
  },
  ["Ashes"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-015",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/ashes.png",
    ["rs_name"] = "ashes",
    ["name"] = "rs-ashes",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 1,
    ["low_alch"] = 0,
    ["examine"] = "A heap of ashes.",
    ["locale_name"] = "Ashes",
  },
  ["Guthix rest"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-018",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/guthix_rest.png",
    ["rs_name"] = "guthix_rest",
    ["name"] = "rs-guthix-rest",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 30,
    ["low_alch"] = 20,
    ["examine"] = "A vial of Guthix Rest.",
    ["locale_name"] = "Guthix rest",
  },
  ["Restore potion"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-022",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/restore_potion.png",
    ["rs_name"] = "restore_potion",
    ["name"] = "rs-restore-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 66,
    ["low_alch"] = 44,
    ["examine"] = "3 doses of restore potion.",
    ["locale_name"] = "Restore potion",
  },
  ["Red spiders' eggs"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-022",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/red_spiders'_eggs.png",
    ["rs_name"] = "red_spiders'_eggs",
    ["name"] = "rs-red-spiders'-eggs",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 4,
    ["low_alch"] = 2,
    ["examine"] = "The red eggs of a spider. Used in Herblore (22).",
    ["locale_name"] = "Red spiders' eggs",
  },
  ["Guthix balance"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-022-b",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/guthix_balance.png",
    ["rs_name"] = "guthix_balance",
    ["name"] = "rs-guthix-balance",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 120,
    ["low_alch"] = 80,
    ["examine"] = "A potion of harralander, red spiders eggs, garlic and silver dust.",
    ["locale_name"] = "Guthix balance",
  },
  ["Garlic"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-022-a",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/garlic.png",
    ["rs_name"] = "garlic",
    ["name"] = "rs-garlic",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 1,
    ["low_alch"] = 1,
    ["examine"] = "Deters vampyres.",
    ["locale_name"] = "Garlic",
  },
  ["Silver dust"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-022-b",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/silver_dust.png",
    ["rs_name"] = "silver_dust",
    ["name"] = "rs-silver-dust",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 120,
    ["low_alch"] = 80,
    ["examine"] = "It's ground up silver.",
    ["locale_name"] = "Silver dust",
  },
  ["Energy potion"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-026",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/energy_potion.png",
    ["rs_name"] = "energy_potion",
    ["name"] = "rs-energy-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 87,
    ["low_alch"] = 28,
    ["examine"] = "3 doses of energy potion.",
    ["locale_name"] = "Energy potion",
  },
  ["Chocolate dust"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-026-b",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/chocolate_dust.png",
    ["rs_name"] = "chocolate_dust",
    ["name"] = "rs-chocolate-dust",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 12,
    ["low_alch"] = 8,
    ["examine"] = "It's ground up chocolate. Used in Cooking (1), Herblore (26).",
    ["locale_name"] = "Chocolate dust",
  },
  ["Chocolate bar"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-026-a",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/chocolate_bar.png",
    ["rs_name"] = "chocolate_bar",
    ["name"] = "rs-chocolate-bar",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 12,
    ["low_alch"] = 8,
    ["examine"] = "Mmmmmmm chocolate.",
    ["locale_name"] = "Chocolate bar",
  },
  ["Agility potion"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-034",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/agility_potion.png",
    ["rs_name"] = "agility_potion",
    ["name"] = "rs-agility-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 60,
    ["low_alch"] = 40,
    ["examine"] = "3 doses of agility potion.",
    ["locale_name"] = "Agility potion",
  },
  ["Toad's legs"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-034",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/toad's_legs.png",
    ["rs_name"] = "toad's_legs",
    ["name"] = "rs-toad's-legs",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 1,
    ["low_alch"] = 0,
    ["examine"] = "They're a gnome delicacy apparently.",
    ["locale_name"] = "Toad's legs",
  },
  ["Combat potion"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-036",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/combat_potion.png",
    ["rs_name"] = "combat_potion",
    ["name"] = "rs-combat-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 96,
    ["low_alch"] = 64,
    ["examine"] = "3 doses of combat potion.",
    ["locale_name"] = "Combat potion",
  },
  ["Goat horn dust"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-036",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/goat_horn_dust.png",
    ["rs_name"] = "goat_horn_dust",
    ["name"] = "rs-goat-horn-dust",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 7,
    ["low_alch"] = 4,
    ["examine"] = "Finely ground desert goat horn.",
    ["locale_name"] = "Goat horn dust",
  },
  ["Prayer potion"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-038",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/prayer_potion.png",
    ["rs_name"] = "prayer_potion",
    ["name"] = "rs-prayer-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 114,
    ["low_alch"] = 60,
    ["examine"] = "3 doses of prayer restore potion.",
    ["locale_name"] = "Prayer potion",
  },
  ["Snape grass"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-038",
    ["stack_size"] = 200,
    ["icon_size"] = 34,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/snape_grass.png",
    ["rs_name"] = "snape_grass",
    ["name"] = "rs-snape-grass",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 6,
    ["low_alch"] = 4,
    ["examine"] = "Strange spiky grass.",
    ["locale_name"] = "Snape grass",
  },
  ["Summoning potion"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-040",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/summoning_potion.png",
    ["rs_name"] = "summoning_potion",
    ["name"] = "rs-summoning-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 68,
    ["low_alch"] = 76,
    ["examine"] = "3 Doses of Summoning potion.",
    ["locale_name"] = "Summoning potion",
  },
  ["Cockatrice egg"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-040",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/cockatrice_egg.png",
    ["rs_name"] = "cockatrice_egg",
    ["name"] = "rs-cockatrice-egg",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 60,
    ["low_alch"] = 40,
    ["examine"] = "A stripy brown egg.",
    ["locale_name"] = "Cockatrice egg",
  },
  ["Crafting potion"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-042",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/crafting_potion.png",
    ["rs_name"] = "crafting_potion",
    ["name"] = "rs-crafting-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 31,
    ["low_alch"] = 42,
    ["examine"] = "3 doses of crafting potion.",
    ["locale_name"] = "Crafting potion",
  },
  ["Frog spawn"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-042",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/frog_spawn.png",
    ["rs_name"] = "frog_spawn",
    ["name"] = "rs-frog-spawn",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 3,
    ["low_alch"] = 2,
    ["examine"] = "That's disgusting!",
    ["locale_name"] = "Frog spawn",
  },
  ["Divination potion"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-043",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/divination_potion.png",
    ["rs_name"] = "divination_potion",
    ["name"] = "rs-divination-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 129,
    ["low_alch"] = 20,
    ["examine"] = "3 doses of divination potion.",
    ["locale_name"] = "Divination potion",
  },
  ["Rabbit foot"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-043",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/rabbit_foot.png",
    ["rs_name"] = "rabbit_foot",
    ["name"] = "rs-rabbit-foot",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 18,
    ["low_alch"] = 12,
    ["examine"] = "This could be put on a string and worn for luck.",
    ["locale_name"] = "Rabbit foot",
  },
  ["Super attack"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-045",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/super_attack.png",
    ["rs_name"] = "super_attack",
    ["name"] = "rs-super-attack",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 108,
    ["low_alch"] = 90,
    ["examine"] = "3 doses of super attack potion.",
    ["locale_name"] = "Super attack",
  },
  ["Super antipoison"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-048",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/super_antipoison.png",
    ["rs_name"] = "super_antipoison",
    ["name"] = "rs-super-antipoison",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 86,
    ["low_alch"] = 57,
    ["examine"] = "3 doses of super antipoison potion.",
    ["locale_name"] = "Super antipoison",
  },
  ["Fishing potion"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-050",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/fishing_potion.png",
    ["rs_name"] = "fishing_potion",
    ["name"] = "rs-fishing-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 90,
    ["low_alch"] = 100,
    ["examine"] = "3 doses of fishing potion.",
    ["locale_name"] = "Fishing potion",
  },
  ["Super energy"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-052",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/super_energy.png",
    ["rs_name"] = "super_energy",
    ["name"] = "rs-super-energy",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 54,
    ["low_alch"] = 92,
    ["examine"] = "3 doses of super energy potion.",
    ["locale_name"] = "Super energy",
  },
  ["Mort myre fungus"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-052",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/mort_myre_fungus.png",
    ["rs_name"] = "mort_myre_fungus",
    ["name"] = "rs-mort-myre-fungus",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 0,
    ["low_alch"] = 0,
    ["examine"] = "A mushroom from the swamps of Mort Myre.",
    ["locale_name"] = "Mort myre fungus",
  },
  ["Hunter potion"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-053",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/hunter_potion.png",
    ["rs_name"] = "hunter_potion",
    ["name"] = "rs-hunter-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 7,
    ["low_alch"] = 4,
    ["examine"] = "3 doses of hunter potion.",
    ["locale_name"] = "Hunter potion",
  },
  ["Kebbit teeth dust"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-053",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/kebbit_teeth_dust.png",
    ["rs_name"] = "kebbit_teeth_dust",
    ["name"] = "rs-kebbit-teeth-dust",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 96,
    ["low_alch"] = 64,
    ["examine"] = "Previously a kebbit-sized set of dentures.",
    ["locale_name"] = "Kebbit teeth dust",
  },
  ["Runecrafting potion"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-054",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/runecrafting_potion.png",
    ["rs_name"] = "runecrafting_potion",
    ["name"] = "rs-runecrafting-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 63,
    ["low_alch"] = 20,
    ["examine"] = "3 doses of runecrafting potion.",
    ["locale_name"] = "Runecrafting potion",
  },
  ["Summerdown wool"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-054",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/summerdown_wool.png",
    ["rs_name"] = "summerdown_wool",
    ["name"] = "rs-summerdown-wool",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 96,
    ["low_alch"] = 64,
    ["examine"] = "From the red sheep of the family. Used to mix runecrafting potions.",
    ["locale_name"] = "Summerdown wool",
  },
  ["Super strength"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-055",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/super_strength.png",
    ["rs_name"] = "super_strength",
    ["name"] = "rs-super-strength",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 165,
    ["low_alch"] = 110,
    ["examine"] = "3 doses of super strength potion.",
    ["locale_name"] = "Super strength",
  },
  ["Luck potion"] = {
    ["subgroup"] = "rs-regular-potions",
    ["order"] = "rs-potion-001-regular-057",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/luck_potion.png",
    ["rs_name"] = "luck_potion",
    ["name"] = "rs-luck-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 3000,
    ["low_alch"] = 2000,
    ["examine"] = "Provides the effects of the Ring of wealth. If only there was a potion that made me magnetically attractive as well.",
    ["locale_name"] = "Luck potion",
  },
  ["Crushed dragonstone"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-057",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/crushed_dragonstone.png",
    ["rs_name"] = "crushed_dragonstone",
    ["name"] = "rs-crushed-dragonstone",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 31,
    ["low_alch"] = 20,
    ["examine"] = "Finely ground dragonstone gem.",
    ["locale_name"] = "Crushed dragonstone",
  },
  ["Fletching potion"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-058",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/fletching_potion.png",
    ["rs_name"] = "fletching_potion",
    ["name"] = "rs-fletching-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 129,
    ["low_alch"] = 20,
    ["examine"] = "3 doses of fletching potion.",
    ["locale_name"] = "Fletching potion",
  },
  ["Wimpy feather"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-058",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/wimpy_feather.png",
    ["rs_name"] = "wimpy_feather",
    ["name"] = "rs-wimpy-feather",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 15,
    ["low_alch"] = 10,
    ["examine"] = "More fluff than feather.",
    ["locale_name"] = "Wimpy feather",
  },
  ["Weapon poison"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-060",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/weapon_poison.png",
    ["rs_name"] = "weapon_poison",
    ["name"] = "rs-weapon-poison",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 115,
    ["low_alch"] = 38,
    ["examine"] = "A vial of weapon poison.",
    ["locale_name"] = "Weapon poison",
  },
  ["Dragon scale dust"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-060",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/dragon_scale_dust.png",
    ["rs_name"] = "dragon_scale_dust",
    ["name"] = "rs-dragon-scale-dust",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 31,
    ["low_alch"] = 20,
    ["examine"] = "Finely ground scale of Dragon.",
    ["locale_name"] = "Dragon scale dust",
  },
  ["Super restore"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-063",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/super_restore.png",
    ["rs_name"] = "super_restore",
    ["name"] = "rs-super-restore",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 72,
    ["low_alch"] = 96,
    ["examine"] = "3 doses of super restore potion.",
    ["locale_name"] = "Super restore",
  },
  ["Super hunter"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-064",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/super_hunter.png",
    ["rs_name"] = "super_hunter",
    ["name"] = "rs-super-hunter",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 81,
    ["low_alch"] = 54,
    ["examine"] = "3 doses of super hunter potion.",
    ["locale_name"] = "Super hunter",
  },
  ["Rabbit teeth"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-064",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/rabbit_teeth.png",
    ["rs_name"] = "rabbit_teeth",
    ["name"] = "rs-rabbit-teeth",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 96,
    ["low_alch"] = 64,
    ["examine"] = "Don't worry, rabbit teeth typically grow back. Used to mix super hunter potions.",
    ["locale_name"] = "Rabbit teeth",
  },
  ["Camouflage potion"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-065",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/camouflage_potion.png",
    ["rs_name"] = "camouflage_potion",
    ["name"] = "rs-camouflage-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 3000,
    ["low_alch"] = 2000,
    ["examine"] = "3 doses of Camouflage potion.",
    ["locale_name"] = "Camouflage potion",
  },
  ["Black salamander"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-065",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/black_salamander.png",
    ["rs_name"] = "black_salamander",
    ["name"] = "rs-black-salamander",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 120,
    ["low_alch"] = 80,
    ["examine"] = "Slightly slimy and somewhat menacing.",
    ["locale_name"] = "Black salamander",
  },
  ["Super defence"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-066",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/super_defence.png",
    ["rs_name"] = "super_defence",
    ["name"] = "rs-super-defence",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 158,
    ["low_alch"] = 105,
    ["examine"] = "3 doses of super defence potion.",
    ["locale_name"] = "Super defence",
  },
  ["White berries"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-066",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/white_berries.png",
    ["rs_name"] = "white_berries",
    ["name"] = "rs-white-berries",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 6,
    ["low_alch"] = 4,
    ["examine"] = "Sour berries, used in potions.",
    ["locale_name"] = "White berries",
  },
  ["Antipoison+"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-068",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/antipoison+.png",
    ["rs_name"] = "antipoison+",
    ["name"] = "rs-antipoison+",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 216,
    ["low_alch"] = 86,
    ["examine"] = "3 doses of extra-strong antipoison potion.",
    ["locale_name"] = "Antipoison+",
  },
  ["Antifire"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-069",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/antifire.png",
    ["rs_name"] = "antifire",
    ["name"] = "rs-antifire",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 118,
    ["low_alch"] = 79,
    ["examine"] = "3 doses of anti-firebreath potion.",
    ["locale_name"] = "Antifire",
  },
  ["Super divination"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-070",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/super_divination.png",
    ["rs_name"] = "super_divination",
    ["name"] = "rs-super-divination",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 108,
    ["low_alch"] = 36,
    ["examine"] = "3 doses of super divination potion.",
    ["locale_name"] = "Super divination",
  },
  ["Zygomite fruit"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-070",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/zygomite_fruit.png",
    ["rs_name"] = "zygomite_fruit",
    ["name"] = "rs-zygomite-fruit",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 96,
    ["low_alch"] = 64,
    ["examine"] = "You don't want to know what this is. Used to mix super divination potions.",
    ["locale_name"] = "Zygomite fruit",
  },
  ["Super ranging potion"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-072",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/super_ranging_potion.png",
    ["rs_name"] = "super_ranging_potion",
    ["name"] = "rs-super-ranging-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 129,
    ["low_alch"] = 115,
    ["examine"] = "3 doses of super ranging potion.",
    ["locale_name"] = "Super ranging potion",
  },
  ["Wine of Zamorak"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-072-a",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/wine_of_zamorak.png",
    ["rs_name"] = "wine_of_zamorak",
    ["name"] = "rs-wine-of-zamorak",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 0,
    ["low_alch"] = 0,
    ["examine"] = "A jug full of Wine of Zamorak.",
    ["locale_name"] = "Wine of Zamorak",
  },
  ["Weapon poison+"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-073",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/weapon_poison+.png",
    ["rs_name"] = "weapon_poison+",
    ["name"] = "rs-weapon-poison+",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 115,
    ["low_alch"] = 38,
    ["examine"] = "A vial of extra-strong weapon poison.",
    ["locale_name"] = "Weapon poison+",
  },
  ["Super runecrafting"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-075",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/super_runecrafting.png",
    ["rs_name"] = "super_runecrafting",
    ["name"] = "rs-super-runecrafting",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 135,
    ["low_alch"] = 90,
    ["examine"] = "3 doses of super runecrafting potion.",
    ["locale_name"] = "Super runecrafting",
  },
  ["Yak milk"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-075",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/yak_milk.png",
    ["rs_name"] = "yak_milk",
    ["name"] = "rs-yak-milk",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 96,
    ["low_alch"] = 64,
    ["examine"] = "Helps with 'dri' mouth. Used to mix super runecrafting potions.",
    ["locale_name"] = "Yak milk",
  },
  ["Super magic potion"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-076",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/super_magic_potion.png",
    ["rs_name"] = "super_magic_potion",
    ["name"] = "rs-super-magic-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 150,
    ["low_alch"] = 120,
    ["examine"] = "3 doses of super magic potion.",
    ["locale_name"] = "Super magic potion",
  },
  ["Potato cactus"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-076",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/potato_cactus.png",
    ["rs_name"] = "potato_cactus",
    ["name"] = "rs-potato-cactus",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 0,
    ["low_alch"] = 0,
    ["examine"] = "How am I supposed to eat that? Used in Herblore(76), Summoning(25).",
    ["locale_name"] = "Potato cactus",
  },
  ["Invention potion"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-077-a",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/invention_potion.png",
    ["rs_name"] = "invention_potion",
    ["name"] = "rs-invention-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 63,
    ["low_alch"] = 86,
    ["examine"] = "3 doses of invention potion.",
    ["locale_name"] = "Invention potion",
  },
  ["Chinchompa residue"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-077-a",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/chinchompa_residue.png",
    ["rs_name"] = "chinchompa_residue",
    ["name"] = "rs-chinchompa-residue",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 96,
    ["low_alch"] = 64,
    ["examine"] = "What remains of exploded chins. Used to mix invention potions.",
    ["locale_name"] = "Chinchompa residue",
  },
  ["Stamina potion"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-077-b",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/stamina_potion.png",
    ["rs_name"] = "stamina_potion",
    ["name"] = "rs-stamina-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 165,
    ["low_alch"] = 66,
    ["examine"] = "3 doses of stamina potion.",
    ["locale_name"] = "Stamina potion",
  },
  ["Zamorak brew"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-078",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/zamorak_brew.png",
    ["rs_name"] = "zamorak_brew",
    ["name"] = "rs-zamorak-brew",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 90,
    ["low_alch"] = 60,
    ["examine"] = "3 doses of Zamorak brew.",
    ["locale_name"] = "Zamorak brew",
  },
  ["Jangerberries"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-078",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/jangerberries.png",
    ["rs_name"] = "jangerberries",
    ["name"] = "rs-jangerberries",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 0,
    ["low_alch"] = 0,
    ["examine"] = "They don't look very ripe.",
    ["locale_name"] = "Jangerberries",
  },
  ["Antipoison++"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-079",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/antipoison++.png",
    ["rs_name"] = "antipoison++",
    ["name"] = "rs-antipoison++",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 86,
    ["low_alch"] = 57,
    ["examine"] = "3 doses of super-strong antipoison potion.",
    ["locale_name"] = "Antipoison++",
  },
  ["Extreme hunter"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-080",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/extreme_hunter.png",
    ["rs_name"] = "extreme_hunter",
    ["name"] = "rs-extreme-hunter",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 54,
    ["low_alch"] = 72,
    ["examine"] = "3 doses of extreme hunter potion.",
    ["locale_name"] = "Extreme hunter",
  },
  ["Bull horns"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-080",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/bull_horns.png",
    ["rs_name"] = "bull_horns",
    ["name"] = "rs-bull-horns",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 96,
    ["low_alch"] = 64,
    ["examine"] = "I'm guessing you messed with the bull. Used to mix extreme hunter potions.",
    ["locale_name"] = "Bull horns",
  },
  ["Saradomin brew"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-081",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/saradomin_brew.png",
    ["rs_name"] = "saradomin_brew",
    ["name"] = "rs-saradomin-brew",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 75,
    ["low_alch"] = 50,
    ["examine"] = "3 doses of Saradomin brew.",
    ["locale_name"] = "Saradomin brew",
  },
  ["Crushed nest"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-081",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/crushed_nest.png",
    ["rs_name"] = "crushed_nest",
    ["name"] = "rs-crushed-nest",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 0,
    ["low_alch"] = 0,
    ["examine"] = "A crushed bird's nest.",
    ["locale_name"] = "Crushed nest",
  },
  ["Weapon poison++"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-082-b",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/weapon_poison++.png",
    ["rs_name"] = "weapon_poison++",
    ["name"] = "rs-weapon-poison++",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 345,
    ["low_alch"] = 115,
    ["examine"] = "A vial of super-strong weapon poison.",
    ["locale_name"] = "Weapon poison++",
  },
  ["Aggression potion"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-082-b",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/aggression_potion.png",
    ["rs_name"] = "aggression_potion",
    ["name"] = "rs-aggression-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 3000,
    ["low_alch"] = 2000,
    ["examine"] = "3 doses of Aggression potion.",
    ["locale_name"] = "Aggression potion",
  },
  ["Searing ashes"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-082-b",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/searing_ashes.png",
    ["rs_name"] = "searing_ashes",
    ["name"] = "rs-searing-ashes",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 1,
    ["low_alch"] = 0,
    ["examine"] = "A heap of ashes from a fiery creature.",
    ["locale_name"] = "Searing ashes",
  },
  ["Adrenaline potion"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-084",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/adrenaline_potion.png",
    ["rs_name"] = "adrenaline_potion",
    ["name"] = "rs-adrenaline-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 66,
    ["low_alch"] = 44,
    ["examine"] = "3 doses of adrenaline potion.",
    ["locale_name"] = "Adrenaline potion",
  },
  ["Papaya fruit"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-084",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/papaya_fruit.png",
    ["rs_name"] = "papaya_fruit",
    ["name"] = "rs-papaya-fruit",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 38,
    ["low_alch"] = 25,
    ["examine"] = "Looks delicious.",
    ["locale_name"] = "Papaya fruit",
  },
  ["Super antifire"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-085",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/super_antifire.png",
    ["rs_name"] = "super_antifire",
    ["name"] = "rs-super-antifire",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 132,
    ["low_alch"] = 88,
    ["examine"] = "3 doses of super antifire potion.",
    ["locale_name"] = "Super antifire",
  },
  ["Phoenix feather"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-085",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/phoenix_feather.png",
    ["rs_name"] = "phoenix_feather",
    ["name"] = "rs-phoenix-feather",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 0,
    ["low_alch"] = 0,
    ["examine"] = "A long feather patterned like a flame.",
    ["locale_name"] = "Phoenix feather",
  },
  ["Super adrenaline potion"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-087",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/super_adrenaline_potion.png",
    ["rs_name"] = "super_adrenaline_potion",
    ["name"] = "rs-super-adrenaline-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 66,
    ["low_alch"] = 88,
    ["examine"] = "3 doses of super adrenaline potion.",
    ["locale_name"] = "Super adrenaline potion",
  },
  ["Adrenaline crystal"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-087",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/adrenaline_crystal.png",
    ["rs_name"] = "adrenaline_crystal",
    ["name"] = "rs-adrenaline-crystal",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 2400,
    ["low_alch"] = 1600,
    ["examine"] = "Add this to adrenaline and replenishment potions to upgrade them to a superior version.",
    ["locale_name"] = "Adrenaline crystal",
  },
  ["Super invention"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-087",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/super_invention.png",
    ["rs_name"] = "super_invention",
    ["name"] = "rs-super-invention",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 108,
    ["low_alch"] = 54,
    ["examine"] = "3 doses of super invention potion.",
    ["locale_name"] = "Super invention",
  },
  ["Spider fangs"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-087",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/spider_fangs.png",
    ["rs_name"] = "spider_fangs",
    ["name"] = "rs-spider-fangs",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 96,
    ["low_alch"] = 64,
    ["examine"] = "Can also be used to liquidise your dinner. Used to mix super invention potions.",
    ["locale_name"] = "Spider fangs",
  },
  ["Extreme attack"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-088",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/extreme_attack.png",
    ["rs_name"] = "extreme_attack",
    ["name"] = "rs-extreme-attack",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 66,
    ["low_alch"] = 44,
    ["examine"] = "3 doses of extreme attack potion.",
    ["locale_name"] = "Extreme attack",
  },
  ["Extreme strength"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-089-a",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/extreme_strength.png",
    ["rs_name"] = "extreme_strength",
    ["name"] = "rs-extreme-strength",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 99,
    ["low_alch"] = 110,
    ["examine"] = "3 doses of extreme strength potion.",
    ["locale_name"] = "Extreme strength",
  },
  ["Extreme divination"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-089-b",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/extreme_divination.png",
    ["rs_name"] = "extreme_divination",
    ["name"] = "rs-extreme-divination",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 81,
    ["low_alch"] = 90,
    ["examine"] = "3 doses of extreme divination potion.",
    ["locale_name"] = "Extreme divination",
  },
  ["Yak tuft"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-089-b",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/yak_tuft.png",
    ["rs_name"] = "yak_tuft",
    ["name"] = "rs-yak-tuft",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 96,
    ["low_alch"] = 64,
    ["examine"] = "Also doubles up as a handy and stylish toupee. Used to mix extreme divination potions.",
    ["locale_name"] = "Yak tuft",
  },
  ["Extreme defence"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-090-a",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/extreme_defence.png",
    ["rs_name"] = "extreme_defence",
    ["name"] = "rs-extreme-defence",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 99,
    ["low_alch"] = 88,
    ["examine"] = "3 doses of extreme defence potion.",
    ["locale_name"] = "Extreme defence",
  },
  ["Extended super antifire"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-090-b",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/extended_super_antifire.png",
    ["rs_name"] = "extended_super_antifire",
    ["name"] = "rs-extended-super-antifire",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 66,
    ["low_alch"] = 44,
    ["examine"] = "3 doses of extended super antifire potion.",
    ["locale_name"] = "Extended super antifire",
  },
  ["Extreme magic"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-091-a",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/extreme_magic.png",
    ["rs_name"] = "extreme_magic",
    ["name"] = "rs-extreme-magic",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 132,
    ["low_alch"] = 44,
    ["examine"] = "3 doses of extreme magic potion.",
    ["locale_name"] = "Extreme magic",
  },
  ["Ground mud runes"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-091-a",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/ground_mud_runes.png",
    ["rs_name"] = "ground_mud_runes",
    ["name"] = "rs-ground-mud-runes",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 0,
    ["low_alch"] = 0,
    ["examine"] = "Mud runes ground into a powder.",
    ["locale_name"] = "Ground mud runes",
  },
  ["Extreme runecrafting"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-091-b",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/extreme_runecrafting.png",
    ["rs_name"] = "extreme_runecrafting",
    ["name"] = "rs-extreme-runecrafting",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 81,
    ["low_alch"] = 72,
    ["examine"] = "3 doses of extreme runecrafting potion.",
    ["locale_name"] = "Extreme runecrafting",
  },
  ["Spider venom"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-091-b",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/spider_venom.png",
    ["rs_name"] = "spider_venom",
    ["name"] = "rs-spider-venom",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 96,
    ["low_alch"] = 64,
    ["examine"] = "Do not ingest. Used to mix extreme runecrafting potions.",
    ["locale_name"] = "Spider venom",
  },
  ["Extreme ranging"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-092",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/extreme_ranging.png",
    ["rs_name"] = "extreme_ranging",
    ["name"] = "rs-extreme-ranging",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 99,
    ["low_alch"] = 88,
    ["examine"] = "3 doses of extreme ranging potion.",
    ["locale_name"] = "Extreme ranging",
  },
  ["Grenwall spikes"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-092",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/grenwall_spikes.png",
    ["rs_name"] = "grenwall_spikes",
    ["name"] = "rs-grenwall-spikes",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 120,
    ["low_alch"] = 80,
    ["examine"] = "Spikes from a grenwall.",
    ["locale_name"] = "Grenwall spikes",
  },
  ["Super Saradomin brew"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-093-a",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/super_saradomin_brew.png",
    ["rs_name"] = "super_saradomin_brew",
    ["name"] = "rs-super-saradomin-brew",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 105,
    ["low_alch"] = 60,
    ["examine"] = "3 doses of super Saradomin brew.",
    ["locale_name"] = "Super Saradomin brew",
  },
  ["Wine of Saradomin"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-072-b",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/wine_of_saradomin.png",
    ["rs_name"] = "wine_of_saradomin",
    ["name"] = "rs-wine-of-saradomin",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 0,
    ["low_alch"] = 0,
    ["examine"] = "It's full of wine of Saradomin.",
    ["locale_name"] = "Wine of Saradomin",
  },
  ["Super Zamorak brew"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-093-b",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/super_zamorak_brew.png",
    ["rs_name"] = "super_zamorak_brew",
    ["name"] = "rs-super-zamorak-brew",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 75,
    ["low_alch"] = 50,
    ["examine"] = "3 doses of super Zamorak brew.",
    ["locale_name"] = "Super Zamorak brew",
  },
  ["Super Guthix rest"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-093-c",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/super_guthix_rest.png",
    ["rs_name"] = "super_guthix_rest",
    ["name"] = "rs-super-guthix-rest",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 75,
    ["low_alch"] = 70,
    ["examine"] = "A vial of super Guthix rest.",
    ["locale_name"] = "Super Guthix rest",
  },
  ["Wine of Guthix"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-072-c",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/wine_of_guthix.png",
    ["rs_name"] = "wine_of_guthix",
    ["name"] = "rs-wine-of-guthix",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 0,
    ["low_alch"] = 0,
    ["examine"] = "It's full of wine of Guthix.",
    ["locale_name"] = "Wine of Guthix",
  },
  ["Super prayer"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-094-a",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/super_prayer.png",
    ["rs_name"] = "super_prayer",
    ["name"] = "rs-super-prayer",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 99,
    ["low_alch"] = 88,
    ["examine"] = "3 doses of super prayer potion.",
    ["locale_name"] = "Super prayer",
  },
  ["Wyvern bonemeal"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-094-a",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/wyvern_bonemeal.png",
    ["rs_name"] = "wyvern_bonemeal",
    ["name"] = "rs-wyvern-bonemeal",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 0,
    ["low_alch"] = 0,
    ["examine"] = "A pot of crushed wyvern bones.",
    ["locale_name"] = "Wyvern bonemeal",
  },
  ["Prayer renewal"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-094-b",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/prayer_renewal.png",
    ["rs_name"] = "prayer_renewal",
    ["name"] = "rs-prayer-renewal",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 132,
    ["low_alch"] = 44,
    ["examine"] = "3 doses of prayer renewal potion.",
    ["locale_name"] = "Prayer renewal",
  },
  ["Morchella mushroom"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-094-b",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/morchella_mushroom.png",
    ["rs_name"] = "morchella_mushroom",
    ["name"] = "rs-morchella-mushroom",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 60,
    ["low_alch"] = 40,
    ["examine"] = "They have miraculous properties.",
    ["locale_name"] = "Morchella mushroom",
  },
  ["Extreme invention"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-095",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/extreme_invention.png",
    ["rs_name"] = "extreme_invention",
    ["name"] = "rs-extreme-invention",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 108,
    ["low_alch"] = 36,
    ["examine"] = "3 doses of extreme invention potion.",
    ["locale_name"] = "Extreme invention",
  },
  ["Mycelial webbing"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-095",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/mycelial_webbing.png",
    ["rs_name"] = "mycelial_webbing",
    ["name"] = "rs-mycelial-webbing",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 96,
    ["low_alch"] = 64,
    ["examine"] = "What a tangled web we weave. Used to mix extreme invention potions.",
    ["locale_name"] = "Mycelial webbing",
  },
  ["Overload"] = {
    ["subgroup"] = "rs-regular-potions",
    ["version"] = "(3)",
    ["order"] = "rs-potion-001-regular-096",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/overload.png",
    ["rs_name"] = "overload",
    ["name"] = "rs-overload",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 165,
    ["low_alch"] = 44,
    ["examine"] = "3 doses of overload potion.",
    ["locale_name"] = "Overload",
  },
  ["Grand strength potion"] = {
    ["subgroup"] = "rs-combination-potions",
    ["version"] = "(6)",
    ["order"] = "075",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/grand_strength_potion.png",
    ["rs_name"] = "grand_strength_potion",
    ["name"] = "rs-grand-strength-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 450,
    ["low_alch"] = 600,
    ["examine"] = "6 doses of grand strength potion.",
    ["locale_name"] = "Grand strength potion",
  },
  ["Grand ranging potion"] = {
    ["subgroup"] = "rs-combination-potions",
    ["version"] = "(6)",
    ["order"] = "076",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/grand_ranging_potion.png",
    ["rs_name"] = "grand_ranging_potion",
    ["name"] = "rs-grand-ranging-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 300,
    ["low_alch"] = 100,
    ["examine"] = "6 doses of grand ranging potion.",
    ["locale_name"] = "Grand ranging potion",
  },
  ["Grand magic potion"] = {
    ["subgroup"] = "rs-combination-potions",
    ["version"] = "(6)",
    ["order"] = "077",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/grand_magic_potion.png",
    ["rs_name"] = "grand_magic_potion",
    ["name"] = "rs-grand-magic-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 750,
    ["low_alch"] = 400,
    ["examine"] = "6 doses of grand magic potion.",
    ["locale_name"] = "Grand magic potion",
  },
  ["Grand attack potion"] = {
    ["subgroup"] = "rs-combination-potions",
    ["version"] = "(6)",
    ["order"] = "078",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/grand_attack_potion.png",
    ["rs_name"] = "grand_attack_potion",
    ["name"] = "rs-grand-attack-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 750,
    ["low_alch"] = 100,
    ["examine"] = "6 doses of grand attack potion.",
    ["locale_name"] = "Grand attack potion",
  },
  ["Grand defence potion"] = {
    ["subgroup"] = "rs-combination-potions",
    ["version"] = "(6)",
    ["order"] = "079",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/grand_defence_potion.png",
    ["rs_name"] = "grand_defence_potion",
    ["name"] = "rs-grand-defence-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 750,
    ["low_alch"] = 400,
    ["examine"] = "6 doses of grand defence potion.",
    ["locale_name"] = "Grand defence potion",
  },
  ["Super melee potion"] = {
    ["subgroup"] = "rs-combination-potions",
    ["version"] = "(6)",
    ["order"] = "081",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/super_melee_potion.png",
    ["rs_name"] = "super_melee_potion",
    ["name"] = "rs-super-melee-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 399,
    ["low_alch"] = 800,
    ["examine"] = "6 doses of super melee potion.",
    ["locale_name"] = "Super melee potion",
  },
  ["Super warmaster's potion"] = {
    ["subgroup"] = "rs-combination-potions",
    ["version"] = "(6)",
    ["order"] = "085",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/super_warmaster's_potion.png",
    ["rs_name"] = "super_warmaster's_potion",
    ["name"] = "rs-super-warmaster's-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 750,
    ["low_alch"] = 333,
    ["examine"] = "6 doses of super warmaster's potion.",
    ["locale_name"] = "Super warmaster's potion",
  },
  ["Replenishment potion"] = {
    ["subgroup"] = "rs-combination-potions",
    ["version"] = "(6)",
    ["order"] = "087",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/replenishment_potion.png",
    ["rs_name"] = "replenishment_potion",
    ["name"] = "rs-replenishment-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 1800,
    ["low_alch"] = 600,
    ["examine"] = "Restores drained stats and a portion of your adrenaline. 6 doses.",
    ["locale_name"] = "Replenishment potion",
  },
  ["Wyrmfire potion"] = {
    ["subgroup"] = "rs-combination-potions",
    ["version"] = "(6)",
    ["order"] = "089",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/wyrmfire_potion.png",
    ["rs_name"] = "wyrmfire_potion",
    ["name"] = "rs-wyrmfire-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 900,
    ["low_alch"] = 800,
    ["examine"] = "Protects against dragon and wyvern fire. 6 doses.",
    ["locale_name"] = "Wyrmfire potion",
  },
  ["Enhanced replenishment potion"] = {
    ["subgroup"] = "rs-combination-potions",
    ["version"] = "(6)",
    ["order"] = "090",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/enhanced_replenishment_potion.png",
    ["rs_name"] = "enhanced_replenishment_potion",
    ["name"] = "rs-enhanced-replenishment-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 600,
    ["low_alch"] = 200,
    ["examine"] = "Restores drained stats and an enhanced portion of your adrenaline. 6 doses.",
    ["locale_name"] = "Enhanced replenishment potion",
  },
  ["Extreme brawler's potion"] = {
    ["subgroup"] = "rs-combination-potions",
    ["version"] = "(6)",
    ["order"] = "091-a",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/extreme_brawler's_potion.png",
    ["rs_name"] = "extreme_brawler's_potion",
    ["name"] = "rs-extreme-brawler's-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 1500,
    ["low_alch"] = 400,
    ["examine"] = "6 doses of extreme brawler's potion.",
    ["locale_name"] = "Extreme brawler's potion",
  },
  ["Extreme battlemage's potion"] = {
    ["subgroup"] = "rs-combination-potions",
    ["version"] = "(6)",
    ["order"] = "091-b",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/extreme_battlemage's_potion.png",
    ["rs_name"] = "extreme_battlemage's_potion",
    ["name"] = "rs-extreme-battlemage's-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 1800,
    ["low_alch"] = 1000,
    ["examine"] = "6 doses of extreme battlemage's potion.",
    ["locale_name"] = "Extreme battlemage's potion",
  },
  ["Extreme sharpshooter's potion"] = {
    ["subgroup"] = "rs-combination-potions",
    ["version"] = "(6)",
    ["order"] = "092",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/extreme_sharpshooter's_potion.png",
    ["rs_name"] = "extreme_sharpshooter's_potion",
    ["name"] = "rs-extreme-sharpshooter's-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 1200,
    ["low_alch"] = 600,
    ["examine"] = "6 doses of extreme sharpshooter's potion.",
    ["locale_name"] = "Extreme sharpshooter's potion",
  },
  ["Extreme warmaster's potion"] = {
    ["subgroup"] = "rs-combination-potions",
    ["version"] = "(6)",
    ["order"] = "093-a",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/extreme_warmaster's_potion.png",
    ["rs_name"] = "extreme_warmaster's_potion",
    ["name"] = "rs-extreme-warmaster's-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 900,
    ["low_alch"] = 1000,
    ["examine"] = "6 doses of extreme warmaster's potion.",
    ["locale_name"] = "Extreme warmaster's potion",
  },
  ["Supreme strength potion"] = {
    ["subgroup"] = "rs-combination-potions",
    ["version"] = "(6)",
    ["order"] = "093-b",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/supreme_strength_potion.png",
    ["rs_name"] = "supreme_strength_potion",
    ["name"] = "rs-supreme-strength-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 1800,
    ["low_alch"] = 600,
    ["examine"] = "6 doses of supreme strength potion.",
    ["locale_name"] = "Supreme strength potion",
  },
  ["Supreme attack potion"] = {
    ["subgroup"] = "rs-combination-potions",
    ["version"] = "(6)",
    ["order"] = "093-c",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/supreme_attack_potion.png",
    ["rs_name"] = "supreme_attack_potion",
    ["name"] = "rs-supreme-attack-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 1800,
    ["low_alch"] = 200,
    ["examine"] = "6 doses of supreme attack potion.",
    ["locale_name"] = "Supreme attack potion",
  },
  ["Supreme defence potion"] = {
    ["subgroup"] = "rs-combination-potions",
    ["version"] = "(6)",
    ["order"] = "093-d",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/supreme_defence_potion.png",
    ["rs_name"] = "supreme_defence_potion",
    ["name"] = "rs-supreme-defence-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 300,
    ["low_alch"] = 1000,
    ["examine"] = "6 doses of supreme defence potion.",
    ["locale_name"] = "Supreme defence potion",
  },
  ["Supreme magic potion"] = {
    ["subgroup"] = "rs-combination-potions",
    ["version"] = "(6)",
    ["order"] = "093-e",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/supreme_magic_potion.png",
    ["rs_name"] = "supreme_magic_potion",
    ["name"] = "rs-supreme-magic-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 1500,
    ["low_alch"] = 800,
    ["examine"] = "6 doses of supreme magic potion.",
    ["locale_name"] = "Supreme magic potion",
  },
  ["Supreme ranging potion"] = {
    ["subgroup"] = "rs-combination-potions",
    ["version"] = "(6)",
    ["order"] = "093-f",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/supreme_ranging_potion.png",
    ["rs_name"] = "supreme_ranging_potion",
    ["name"] = "rs-supreme-ranging-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 300,
    ["low_alch"] = 200,
    ["examine"] = "6 doses of supreme ranging potion.",
    ["locale_name"] = "Supreme ranging potion",
  },
  ["Brightfire potion"] = {
    ["subgroup"] = "rs-combination-potions",
    ["version"] = "(6)",
    ["order"] = "094",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/brightfire_potion.png",
    ["rs_name"] = "brightfire_potion",
    ["name"] = "rs-brightfire-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 1500,
    ["low_alch"] = 400,
    ["examine"] = "Renews your prayer points over time, and protects you from dragonfire. 6 doses.",
    ["locale_name"] = "Brightfire potion",
  },
  ["Super prayer renewal potion"] = {
    ["subgroup"] = "rs-combination-potions",
    ["version"] = "(6)",
    ["order"] = "096",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/super_prayer_renewal_potion.png",
    ["rs_name"] = "super_prayer_renewal_potion",
    ["name"] = "rs-super-prayer-renewal-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 2100,
    ["low_alch"] = 1166,
    ["examine"] = "6 doses of super prayer renewal potion.",
    ["locale_name"] = "Super prayer renewal potion",
  },
  ["Holy overload potion"] = {
    ["subgroup"] = "rs-combination-potions",
    ["version"] = "(6)",
    ["order"] = "097-a",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/holy_overload_potion.png",
    ["rs_name"] = "holy_overload_potion",
    ["name"] = "rs-holy-overload-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 2400,
    ["low_alch"] = 266,
    ["examine"] = "Renews your prayer points over time, and boosts your combat stats. 6 doses.",
    ["locale_name"] = "Holy overload potion",
  },
  ["Searing overload potion"] = {
    ["subgroup"] = "rs-combination-potions",
    ["version"] = "(6)",
    ["order"] = "097-b",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/searing_overload_potion.png",
    ["rs_name"] = "searing_overload_potion",
    ["name"] = "rs-searing-overload-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 2400,
    ["low_alch"] = 1066,
    ["examine"] = "Protects you from dragonfire and boosts your combat stats. 6 doses.",
    ["locale_name"] = "Searing overload potion",
  },
  ["Overload salve"] = {
    ["subgroup"] = "rs-combination-potions",
    ["version"] = "(6)",
    ["order"] = "097-c",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/overload_salve.png",
    ["rs_name"] = "overload_salve",
    ["name"] = "rs-overload-salve",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 1599,
    ["low_alch"] = 533,
    ["examine"] = "Boosts all combat stats, restores prayer points over time, cures poison, and protects from both poison and dragonfire. 6 doses.",
    ["locale_name"] = "Overload salve",
  },
  ["Aggroverload"] = {
    ["subgroup"] = "rs-combination-potions",
    ["version"] = "(6)",
    ["order"] = "097-d",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/aggroverload.png",
    ["rs_name"] = "aggroverload",
    ["name"] = "rs-aggroverload",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 1999,
    ["low_alch"] = 1066,
    ["examine"] = "Greatly boosts all combat stats and causes creatures within a radius to become aggressive.  6 doses.",
    ["locale_name"] = "Aggroverload",
  },
  ["Supreme overload potion"] = {
    ["subgroup"] = "rs-combination-potions",
    ["version"] = "(6)",
    ["order"] = "098",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/supreme_overload_potion.png",
    ["rs_name"] = "supreme_overload_potion",
    ["name"] = "rs-supreme-overload-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 1599,
    ["low_alch"] = 1066,
    ["examine"] = "6 doses of supreme overload potion.",
    ["locale_name"] = "Supreme overload potion",
  },
  ["Supreme overload salve"] = {
    ["subgroup"] = "rs-combination-potions",
    ["version"] = "(6)",
    ["order"] = "99-a",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/supreme_overload_salve.png",
    ["rs_name"] = "supreme_overload_salve",
    ["name"] = "rs-supreme-overload-salve",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 399,
    ["low_alch"] = 1333,
    ["examine"] = "Greatly boosts all combat stats, restores prayer points over time, cures poison, and protects from both poison and dragonfire. 6 doses.",
    ["locale_name"] = "Supreme overload salve",
  },
  ["Perfect plus potion"] = {
    ["subgroup"] = "rs-combination-potions",
    ["version"] = "(6)",
    ["order"] = "099-b",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/perfect_plus_potion.png",
    ["rs_name"] = "perfect_plus_potion",
    ["name"] = "rs-perfect-plus-potion",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 1599,
    ["low_alch"] = 1066,
    ["examine"] = "Grants all perfect skilling potion effects, and increases bonuses from the Voice of Seren. 6 doses.",
    ["locale_name"] = "Perfect plus potion",
  },
  ["Harmony moss"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-099-a",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/harmony_moss.png",
    ["rs_name"] = "harmony_moss",
    ["name"] = "rs-harmony-moss",
    ["type"] = "item",
    ["flags"] = {
    },
    ["examine"] = "Some special elven moss.",
    ["locale_name"] = "Harmony moss",
  },
  ["Crystal tree blossom"] = {
    ["subgroup"] = "rs-herblore-secondaries",
    ["order"] = "rs-potion-001-regular-099-b",
    ["stack_size"] = 50,
    ["icon_size"] = 32,
    ["icon"] = "__RsHerblore__/graphics/icons/auto_generated/crystal_tree_blossom.png",
    ["rs_name"] = "crystal_tree_blossom",
    ["name"] = "rs-crystal-tree-blossom",
    ["type"] = "item",
    ["flags"] = {
    },
    ["examine"] = "The fruit of a crystal tree.",
    ["locale_name"] = "Crystal tree blossom",
  },
}