return {
  ["acorn"] = {
    ["subgroup"] = "rs-farming-seeds",
    ["stack_size"] = 200,
    ["order"] = "rs-seeds-010",
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/acorn.png",
    ["rs_name"] = "acorn",
    ["name"] = "rs-acorn",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 3,
    ["low_alch"] = 2,
    ["examine"] = "Plant this in a plantpot of soil to grow a sapling. Used in Farming (15).",
    ["locale_name"] = "Acorn",
  },
  ["willow seed"] = {
    ["subgroup"] = "rs-farming-seeds",
    ["stack_size"] = 200,
    ["order"] = "rs-seeds-011",
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/willow_seed.png",
    ["rs_name"] = "willow_seed",
    ["name"] = "rs-willow-seed",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 9,
    ["low_alch"] = 6,
    ["examine"] = "Plant this in a plantpot of soil to grow a sapling.",
    ["locale_name"] = "Willow seed",
  },
  ["maple seed"] = {
    ["subgroup"] = "rs-farming-seeds",
    ["stack_size"] = 200,
    ["order"] = "rs-seeds-012",
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/maple_seed.png",
    ["rs_name"] = "maple_seed",
    ["name"] = "rs-maple-seed",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 28,
    ["low_alch"] = 19,
    ["examine"] = "Plant this in a plantpot of soil to grow a sapling.",
    ["locale_name"] = "Maple seed",
  },
  ["yew seed"] = {
    ["subgroup"] = "rs-farming-seeds",
    ["stack_size"] = 200,
    ["order"] = "rs-seeds-013",
    ["icon_size"] = 33,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/yew_seed.png",
    ["rs_name"] = "yew_seed",
    ["name"] = "rs-yew-seed",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 85,
    ["low_alch"] = 57,
    ["examine"] = "Plant this in a plantpot of soil to grow a sapling.",
    ["locale_name"] = "Yew seed",
  },
  ["magic seed"] = {
    ["subgroup"] = "rs-farming-seeds",
    ["stack_size"] = 200,
    ["order"] = "rs-seeds-014",
    ["icon_size"] = 33,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/magic_seed.png",
    ["rs_name"] = "magic_seed",
    ["name"] = "rs-magic-seed",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 253,
    ["low_alch"] = 168,
    ["examine"] = "Plant this in a plantpot of soil to grow a sapling.",
    ["locale_name"] = "Magic seed",
  },
  ["bucket"] = {
    ["subgroup"] = "rs-compost",
    ["stack_size"] = 200,
    ["order"] = "rs-010-bucket-a",
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/bucket.png",
    ["rs_name"] = "bucket",
    ["name"] = "rs-bucket",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 1,
    ["low_alch"] = 0,
    ["examine"] = "It's a wooden bucket.",
    ["locale_name"] = "Bucket",
  },
  ["compost"] = {
    ["subgroup"] = "rs-compost",
    ["stack_size"] = 100,
    ["order"] = "rs-011-compost",
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/compost.png",
    ["rs_name"] = "compost",
    ["name"] = "rs-compost",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 12,
    ["low_alch"] = 8,
    ["examine"] = "Good for plants, helps them grow. Used in Farming (1).",
    ["locale_name"] = "Compost",
  },
  ["supercompost"] = {
    ["subgroup"] = "rs-compost",
    ["stack_size"] = 100,
    ["order"] = "rs-012-supercompost",
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/supercompost.png",
    ["rs_name"] = "supercompost",
    ["name"] = "rs-supercompost",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 51,
    ["low_alch"] = 34,
    ["examine"] = "Super-good for the smallest or largest of plants.",
    ["locale_name"] = "Supercompost",
  },
  ["oak roots"] = {
    ["subgroup"] = "rs-farming-roots",
    ["stack_size"] = 100,
    ["order"] = "rs-010-oak-roots",
    ["icon_size"] = 34,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/oak_roots.png",
    ["rs_name"] = "oak_roots",
    ["name"] = "rs-oak-roots",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 0,
    ["low_alch"] = 0,
    ["examine"] = "The roots of the Oak tree.",
    ["locale_name"] = "Oak roots",
  },
  ["willow roots"] = {
    ["subgroup"] = "rs-farming-roots",
    ["stack_size"] = 100,
    ["order"] = "rs-011-willow-roots",
    ["icon_size"] = 34,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/willow_roots.png",
    ["rs_name"] = "willow_roots",
    ["name"] = "rs-willow-roots",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 0,
    ["low_alch"] = 0,
    ["examine"] = "The roots of the Willow tree.",
    ["locale_name"] = "Willow roots",
  },
  ["maple roots"] = {
    ["subgroup"] = "rs-farming-roots",
    ["stack_size"] = 100,
    ["order"] = "rs-012-maple-roots",
    ["icon_size"] = 34,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/maple_roots.png",
    ["rs_name"] = "maple_roots",
    ["name"] = "rs-maple-roots",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 0,
    ["low_alch"] = 0,
    ["examine"] = "The roots of the Maple tree.",
    ["locale_name"] = "Maple roots",
  },
  ["yew roots"] = {
    ["subgroup"] = "rs-farming-roots",
    ["stack_size"] = 100,
    ["order"] = "rs-013-yew-roots",
    ["icon_size"] = 34,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/yew_roots.png",
    ["rs_name"] = "yew_roots",
    ["name"] = "rs-yew-roots",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 0,
    ["low_alch"] = 0,
    ["examine"] = "The roots of the Yew tree.",
    ["locale_name"] = "Yew roots",
  },
  ["magic roots"] = {
    ["subgroup"] = "rs-farming-roots",
    ["stack_size"] = 100,
    ["order"] = "rs-014-magic-roots",
    ["icon_size"] = 34,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/magic_roots.png",
    ["rs_name"] = "magic_roots",
    ["name"] = "rs-magic-roots",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 0,
    ["low_alch"] = 0,
    ["examine"] = "The roots of the Magic tree.",
    ["locale_name"] = "Magic roots",
  },
  ["Bird's_nest_(seeds_1)"] = {
    ["subgroup"] = "rs-farming-seeds",
    ["stack_size"] = 50,
    ["order"] = "rs-seeds-000-birds-nest-011",
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/bird's_nest_(seeds_1).png",
    ["rs_name"] = "bird's_nest_(seeds_1)",
    ["name"] = "rs-birds-nest",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 0,
    ["low_alch"] = 0,
    ["examine"] = "It's a bird's nest with some seeds in it.",
    ["locale_name"] = "Bird's nest",
  },
  ["Bird's_nest_(empty)"] = {
    ["subgroup"] = "rs-farming-seeds",
    ["stack_size"] = 50,
    ["order"] = "rs-seeds-000-birds-nest-010",
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/bird's_nest_(empty).png",
    ["rs_name"] = "bird's_nest_(empty)",
    ["name"] = "rs-empty-birds-nest",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 0,
    ["low_alch"] = 0,
    ["examine"] = "It's an empty bird's nest.",
    ["locale_name"] = "Empty bird's nest",
  },
  ["Guam seed"] = {
    ["subgroup"] = "rs-herb-seeds",
    ["order"] = "rs-seeds-020-guam-seed",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/guam_seed.png",
    ["rs_name"] = "guam_seed",
    ["name"] = "rs-guam-seed",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 2,
    ["low_alch"] = 1,
    ["examine"] = "A guam seed - plant in a herb patch.",
    ["locale_name"] = "Guam seed",
  },
  ["Grimy guam"] = {
    ["subgroup"] = "rs-grimy-herbs",
    ["order"] = "rs-grimy-herbs-020",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/grimy_guam.png",
    ["rs_name"] = "grimy_guam",
    ["name"] = "rs-grimy-guam",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 18,
    ["low_alch"] = 12,
    ["examine"] = "I need to clean this herb before I can use it.",
    ["locale_name"] = "Grimy guam",
  },
  ["Clean guam"] = {
    ["subgroup"] = "rs-clean-herbs",
    ["order"] = "rs-clean-herbs-020",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/clean_guam.png",
    ["rs_name"] = "clean_guam",
    ["name"] = "rs-clean-guam",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 18,
    ["low_alch"] = 12,
    ["examine"] = "A fresh herb.",
    ["locale_name"] = "Clean guam",
  },
  ["Marrentill seed"] = {
    ["subgroup"] = "rs-herb-seeds",
    ["order"] = "rs-seeds-021-marrentill-seed",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/marrentill_seed.png",
    ["rs_name"] = "marrentill_seed",
    ["name"] = "rs-marrentill-seed",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 3,
    ["low_alch"] = 2,
    ["examine"] = "A marrentill seed - plant in a herb patch. Used in Farming (14).",
    ["locale_name"] = "Marrentill seed",
  },
  ["Grimy marrentill"] = {
    ["subgroup"] = "rs-grimy-herbs",
    ["order"] = "rs-grimy-herbs-021",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/grimy_marrentill.png",
    ["rs_name"] = "grimy_marrentill",
    ["name"] = "rs-grimy-marrentill",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 0,
    ["low_alch"] = 0,
    ["examine"] = "I need to clean this herb before I can use it.",
    ["locale_name"] = "Grimy marrentill",
  },
  ["Clean marrentill"] = {
    ["subgroup"] = "rs-clean-herbs",
    ["order"] = "rs-clean-herbs-021",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/clean_marrentill.png",
    ["rs_name"] = "clean_marrentill",
    ["name"] = "rs-clean-marrentill",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 3,
    ["low_alch"] = 2,
    ["examine"] = "A fresh herb.",
    ["locale_name"] = "Clean marrentill",
  },
  ["Tarromin seed"] = {
    ["subgroup"] = "rs-herb-seeds",
    ["order"] = "rs-seeds-022-tarromin-seed",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/tarromin_seed.png",
    ["rs_name"] = "tarromin_seed",
    ["name"] = "rs-tarromin-seed",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 4,
    ["low_alch"] = 2,
    ["examine"] = "A tarromin seed - plant in a herb patch.",
    ["locale_name"] = "Tarromin seed",
  },
  ["Grimy tarromin"] = {
    ["subgroup"] = "rs-grimy-herbs",
    ["order"] = "rs-grimy-herbs-022",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/grimy_tarromin.png",
    ["rs_name"] = "grimy_tarromin",
    ["name"] = "rs-grimy-tarromin",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 0,
    ["low_alch"] = 0,
    ["examine"] = "I need to clean this herb before I can use it.",
    ["locale_name"] = "Grimy tarromin",
  },
  ["Clean tarromin"] = {
    ["subgroup"] = "rs-clean-herbs",
    ["order"] = "rs-clean-herbs-022",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/clean_tarromin.png",
    ["rs_name"] = "clean_tarromin",
    ["name"] = "rs-clean-tarromin",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 6,
    ["low_alch"] = 4,
    ["examine"] = "A fresh herb.",
    ["locale_name"] = "Clean tarromin",
  },
  ["Harralander seed"] = {
    ["subgroup"] = "rs-herb-seeds",
    ["order"] = "rs-seeds-023-harralander-seed",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/harralander_seed.png",
    ["rs_name"] = "harralander_seed",
    ["name"] = "rs-harralander-seed",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 7,
    ["low_alch"] = 4,
    ["examine"] = "A harralander seed - plant in a herb patch. Used in Farming (26).",
    ["locale_name"] = "Harralander seed",
  },
  ["Grimy harralander"] = {
    ["subgroup"] = "rs-grimy-herbs",
    ["order"] = "rs-grimy-herbs-023",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/grimy_harralander.png",
    ["rs_name"] = "grimy_harralander",
    ["name"] = "rs-grimy-harralander",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 0,
    ["low_alch"] = 0,
    ["examine"] = "I need to clean this herb before I can use it.",
    ["locale_name"] = "Grimy harralander",
  },
  ["Clean harralander"] = {
    ["subgroup"] = "rs-clean-herbs",
    ["order"] = "rs-clean-herbs-023",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/clean_harralander.png",
    ["rs_name"] = "clean_harralander",
    ["name"] = "rs-clean-harralander",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 12,
    ["low_alch"] = 8,
    ["examine"] = "A fresh herb.",
    ["locale_name"] = "Clean harralander",
  },
  ["Ranarr seed"] = {
    ["subgroup"] = "rs-herb-seeds",
    ["order"] = "rs-seeds-024-ranarr-seed",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/ranarr_seed.png",
    ["rs_name"] = "ranarr_seed",
    ["name"] = "rs-ranarr-seed",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 11,
    ["low_alch"] = 7,
    ["examine"] = "A ranarr seed - plant in a herb patch.",
    ["locale_name"] = "Ranarr seed",
  },
  ["Grimy ranarr"] = {
    ["subgroup"] = "rs-grimy-herbs",
    ["order"] = "rs-grimy-herbs-024",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/grimy_ranarr.png",
    ["rs_name"] = "grimy_ranarr",
    ["name"] = "rs-grimy-ranarr",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 0,
    ["low_alch"] = 0,
    ["examine"] = "I need to clean this herb before I can use it.",
    ["locale_name"] = "Grimy ranarr",
  },
  ["Clean ranarr"] = {
    ["subgroup"] = "rs-clean-herbs",
    ["order"] = "rs-clean-herbs-024",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/clean_ranarr.png",
    ["rs_name"] = "clean_ranarr",
    ["name"] = "rs-clean-ranarr",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 15,
    ["low_alch"] = 10,
    ["examine"] = "A fresh herb.",
    ["locale_name"] = "Clean ranarr",
  },
  ["Toadflax seed"] = {
    ["subgroup"] = "rs-herb-seeds",
    ["order"] = "rs-seeds-025-toadflax-seed",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/toadflax_seed.png",
    ["rs_name"] = "toadflax_seed",
    ["name"] = "rs-toadflax-seed",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 20,
    ["low_alch"] = 13,
    ["examine"] = "A toadflax seed - plant in a herb patch.",
    ["locale_name"] = "Toadflax seed",
  },
  ["Grimy toadflax"] = {
    ["subgroup"] = "rs-grimy-herbs",
    ["order"] = "rs-grimy-herbs-025",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/grimy_toadflax.png",
    ["rs_name"] = "grimy_toadflax",
    ["name"] = "rs-grimy-toadflax",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 0,
    ["low_alch"] = 0,
    ["examine"] = "I need to clean this herb before I can use it.",
    ["locale_name"] = "Grimy toadflax",
  },
  ["Clean toadflax"] = {
    ["subgroup"] = "rs-clean-herbs",
    ["order"] = "rs-clean-herbs-025",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/clean_toadflax.png",
    ["rs_name"] = "clean_toadflax",
    ["name"] = "rs-clean-toadflax",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 28,
    ["low_alch"] = 19,
    ["examine"] = "A fresh herb.",
    ["locale_name"] = "Clean toadflax",
  },
  ["Spirit weed seed"] = {
    ["subgroup"] = "rs-herb-seeds",
    ["order"] = "rs-seeds-026-spirit-weed-seed",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/spirit_weed_seed.png",
    ["rs_name"] = "spirit_weed_seed",
    ["name"] = "rs-spirit-weed-seed",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 10,
    ["low_alch"] = 7,
    ["examine"] = "A seed for spirit weed.",
    ["locale_name"] = "Spirit weed seed",
  },
  ["Grimy spirit weed"] = {
    ["subgroup"] = "rs-grimy-herbs",
    ["order"] = "rs-grimy-herbs-026",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/grimy_spirit_weed.png",
    ["rs_name"] = "grimy_spirit_weed",
    ["name"] = "rs-grimy-spirit-weed",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 0,
    ["low_alch"] = 0,
    ["examine"] = "I need to clean this herb before I can use it.",
    ["locale_name"] = "Grimy spirit weed",
  },
  ["Clean spirit weed"] = {
    ["subgroup"] = "rs-clean-herbs",
    ["order"] = "rs-clean-herbs-026",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/clean_spirit_weed.png",
    ["rs_name"] = "clean_spirit_weed",
    ["name"] = "rs-clean-spirit-weed",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 14,
    ["low_alch"] = 9,
    ["examine"] = "A fresh herb.",
    ["locale_name"] = "Clean spirit weed",
  },
  ["Irit seed"] = {
    ["subgroup"] = "rs-herb-seeds",
    ["order"] = "rs-seeds-027-irit-seed",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/irit_seed.png",
    ["rs_name"] = "irit_seed",
    ["name"] = "rs-irit-seed",
    ["type"] = "item",
    ["flags"] = {
    },
    ["examine"] = "An irit seed - plant in a herb patch.",
    ["locale_name"] = "Irit seed",
  },
  ["Grimy irit"] = {
    ["subgroup"] = "rs-grimy-herbs",
    ["order"] = "rs-grimy-herbs-027",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/grimy_irit.png",
    ["rs_name"] = "grimy_irit",
    ["name"] = "rs-grimy-irit",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 0,
    ["low_alch"] = 0,
    ["examine"] = "I need to clean this herb before I can use it.",
    ["locale_name"] = "Grimy irit",
  },
  ["Clean irit"] = {
    ["subgroup"] = "rs-clean-herbs",
    ["order"] = "rs-clean-herbs-027",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/clean_irit.png",
    ["rs_name"] = "clean_irit",
    ["name"] = "rs-clean-irit",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 24,
    ["low_alch"] = 16,
    ["examine"] = "A fresh herb.",
    ["locale_name"] = "Clean irit",
  },
  ["Wergali seed"] = {
    ["subgroup"] = "rs-herb-seeds",
    ["order"] = "rs-seeds-028-wergali-seed",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/wergali_seed.png",
    ["rs_name"] = "wergali_seed",
    ["name"] = "rs-wergali-seed",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 38,
    ["low_alch"] = 25,
    ["examine"] = "A wergali seed - plant in a herb patch.",
    ["locale_name"] = "Wergali seed",
  },
  ["Grimy wergali"] = {
    ["subgroup"] = "rs-grimy-herbs",
    ["order"] = "rs-grimy-herbs-028",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/grimy_wergali.png",
    ["rs_name"] = "grimy_wergali",
    ["name"] = "rs-grimy-wergali",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 0,
    ["low_alch"] = 0,
    ["examine"] = "I need to clean this herb before I can use it.",
    ["locale_name"] = "Grimy wergali",
  },
  ["Clean wergali"] = {
    ["subgroup"] = "rs-clean-herbs",
    ["order"] = "rs-clean-herbs-028",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/clean_wergali.png",
    ["rs_name"] = "clean_wergali",
    ["name"] = "rs-clean-wergali",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 26,
    ["low_alch"] = 17,
    ["examine"] = "A fresh herb.",
    ["locale_name"] = "Clean wergali",
  },
  ["Avantoe seed"] = {
    ["subgroup"] = "rs-herb-seeds",
    ["order"] = "rs-seeds-029-avantoe-seed",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/avantoe_seed.png",
    ["rs_name"] = "avantoe_seed",
    ["name"] = "rs-avantoe-seed",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 38,
    ["low_alch"] = 25,
    ["examine"] = "An avantoe seed - plant in a herb patch.",
    ["locale_name"] = "Avantoe seed",
  },
  ["Grimy avantoe"] = {
    ["subgroup"] = "rs-grimy-herbs",
    ["order"] = "rs-grimy-herbs-029",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/grimy_avantoe.png",
    ["rs_name"] = "grimy_avantoe",
    ["name"] = "rs-grimy-avantoe",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 0,
    ["low_alch"] = 0,
    ["examine"] = "I need to clean this herb before I can use it.",
    ["locale_name"] = "Grimy avantoe",
  },
  ["Clean avantoe"] = {
    ["subgroup"] = "rs-clean-herbs",
    ["order"] = "rs-clean-herbs-029",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/clean_avantoe.png",
    ["rs_name"] = "clean_avantoe",
    ["name"] = "rs-clean-avantoe",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 28,
    ["low_alch"] = 19,
    ["examine"] = "A fresh herb.",
    ["locale_name"] = "Clean avantoe",
  },
  ["Kwuarm seed"] = {
    ["subgroup"] = "rs-herb-seeds",
    ["order"] = "rs-seeds-030-kwuarm-seed",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/kwuarm_seed.png",
    ["rs_name"] = "kwuarm_seed",
    ["name"] = "rs-kwuarm-seed",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 38,
    ["low_alch"] = 25,
    ["examine"] = "A kwuarm seed - plant in a herb patch.",
    ["locale_name"] = "Kwuarm seed",
  },
  ["Grimy kwuarm"] = {
    ["subgroup"] = "rs-grimy-herbs",
    ["order"] = "rs-grimy-herbs-030",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/grimy_kwuarm.png",
    ["rs_name"] = "grimy_kwuarm",
    ["name"] = "rs-grimy-kwuarm",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 0,
    ["low_alch"] = 0,
    ["examine"] = "I need to clean this herb before I can use it.",
    ["locale_name"] = "Grimy kwuarm",
  },
  ["Clean kwuarm"] = {
    ["subgroup"] = "rs-clean-herbs",
    ["order"] = "rs-clean-herbs-030",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/clean_kwuarm.png",
    ["rs_name"] = "clean_kwuarm",
    ["name"] = "rs-clean-kwuarm",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 32,
    ["low_alch"] = 21,
    ["examine"] = "A fresh herb.",
    ["locale_name"] = "Clean kwuarm",
  },
  ["Bloodweed seed"] = {
    ["subgroup"] = "rs-herb-seeds",
    ["order"] = "rs-seeds-031-bloodweed-seed",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/bloodweed_seed.png",
    ["rs_name"] = "bloodweed_seed",
    ["name"] = "rs-bloodweed-seed",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 38,
    ["low_alch"] = 25,
    ["examine"] = "A blood seed - plant in the herb patch in the wilderness.",
    ["locale_name"] = "Bloodweed seed",
  },
  ["Grimy bloodweed"] = {
    ["subgroup"] = "rs-grimy-herbs",
    ["order"] = "rs-grimy-herbs-031",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/grimy_bloodweed.png",
    ["rs_name"] = "grimy_bloodweed",
    ["name"] = "rs-grimy-bloodweed",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 60,
    ["low_alch"] = 40,
    ["examine"] = "I need to clean this herb before I can use it.",
    ["locale_name"] = "Grimy bloodweed",
  },
  ["Clean bloodweed"] = {
    ["subgroup"] = "rs-clean-herbs",
    ["order"] = "rs-clean-herbs-031",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/clean_bloodweed.png",
    ["rs_name"] = "clean_bloodweed",
    ["name"] = "rs-clean-bloodweed",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 90,
    ["low_alch"] = 60,
    ["examine"] = "A fresh herb.",
    ["locale_name"] = "Clean bloodweed",
  },
  ["Snapdragon seed"] = {
    ["subgroup"] = "rs-herb-seeds",
    ["order"] = "rs-seeds-032-snapdragon-seed",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/snapdragon_seed.png",
    ["rs_name"] = "snapdragon_seed",
    ["name"] = "rs-snapdragon-seed",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 38,
    ["low_alch"] = 25,
    ["examine"] = "A snapdragon seed - plant in a herb patch.",
    ["locale_name"] = "Snapdragon seed",
  },
  ["Grimy snapdragon"] = {
    ["subgroup"] = "rs-grimy-herbs",
    ["order"] = "rs-grimy-herbs-032",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/grimy_snapdragon.png",
    ["rs_name"] = "grimy_snapdragon",
    ["name"] = "rs-grimy-snapdragon",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 0,
    ["low_alch"] = 0,
    ["examine"] = "I need to clean this herb before I can use it.",
    ["locale_name"] = "Grimy snapdragon",
  },
  ["Clean snapdragon"] = {
    ["subgroup"] = "rs-clean-herbs",
    ["order"] = "rs-clean-herbs-032",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/clean_snapdragon.png",
    ["rs_name"] = "clean_snapdragon",
    ["name"] = "rs-clean-snapdragon",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 35,
    ["low_alch"] = 23,
    ["examine"] = "A fresh herb.",
    ["locale_name"] = "Clean snapdragon",
  },
  ["Cadantine seed"] = {
    ["subgroup"] = "rs-herb-seeds",
    ["order"] = "rs-seeds-033-cadantine-seed",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/cadantine_seed.png",
    ["rs_name"] = "cadantine_seed",
    ["name"] = "rs-cadantine-seed",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 38,
    ["low_alch"] = 25,
    ["examine"] = "A cadantine seed - plant in a herb patch.",
    ["locale_name"] = "Cadantine seed",
  },
  ["Grimy cadantine"] = {
    ["subgroup"] = "rs-grimy-herbs",
    ["order"] = "rs-grimy-herbs-033",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/grimy_cadantine.png",
    ["rs_name"] = "grimy_cadantine",
    ["name"] = "rs-grimy-cadantine",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 0,
    ["low_alch"] = 0,
    ["examine"] = "I need to clean this herb before I can use it.",
    ["locale_name"] = "Grimy cadantine",
  },
  ["Clean cadantine"] = {
    ["subgroup"] = "rs-clean-herbs",
    ["order"] = "rs-clean-herbs-033",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/clean_cadantine.png",
    ["rs_name"] = "clean_cadantine",
    ["name"] = "rs-clean-cadantine",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 39,
    ["low_alch"] = 26,
    ["examine"] = "A fresh herb.",
    ["locale_name"] = "Clean cadantine",
  },
  ["Lantadyme seed"] = {
    ["subgroup"] = "rs-herb-seeds",
    ["order"] = "rs-seeds-034-lantadyme-seed",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/lantadyme_seed.png",
    ["rs_name"] = "lantadyme_seed",
    ["name"] = "rs-lantadyme-seed",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 38,
    ["low_alch"] = 25,
    ["examine"] = "A lantadyme seed - plant in a herb patch.",
    ["locale_name"] = "Lantadyme seed",
  },
  ["Grimy lantadyme"] = {
    ["subgroup"] = "rs-grimy-herbs",
    ["order"] = "rs-grimy-herbs-034",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/grimy_lantadyme.png",
    ["rs_name"] = "grimy_lantadyme",
    ["name"] = "rs-grimy-lantadyme",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 0,
    ["low_alch"] = 0,
    ["examine"] = "I need to clean this herb before I can use it.",
    ["locale_name"] = "Grimy lantadyme",
  },
  ["Clean lantadyme"] = {
    ["subgroup"] = "rs-clean-herbs",
    ["order"] = "rs-clean-herbs-034",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/clean_lantadyme.png",
    ["rs_name"] = "clean_lantadyme",
    ["name"] = "rs-clean-lantadyme",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 40,
    ["low_alch"] = 27,
    ["examine"] = "A fresh herb.",
    ["locale_name"] = "Clean lantadyme",
  },
  ["Dwarf weed seed"] = {
    ["subgroup"] = "rs-herb-seeds",
    ["order"] = "rs-seeds-035-dwarf-weed-seed",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/dwarf_weed_seed.png",
    ["rs_name"] = "dwarf_weed_seed",
    ["name"] = "rs-dwarf-weed-seed",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 38,
    ["low_alch"] = 25,
    ["examine"] = "A dwarf weed seed - plant in a herb patch.",
    ["locale_name"] = "Dwarf weed seed",
  },
  ["Grimy dwarf weed"] = {
    ["subgroup"] = "rs-grimy-herbs",
    ["order"] = "rs-grimy-herbs-035",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/grimy_dwarf_weed.png",
    ["rs_name"] = "grimy_dwarf_weed",
    ["name"] = "rs-grimy-dwarf-weed",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 0,
    ["low_alch"] = 0,
    ["examine"] = "I need to clean this herb before I can use it.",
    ["locale_name"] = "Grimy dwarf weed",
  },
  ["Clean dwarf weed"] = {
    ["subgroup"] = "rs-clean-herbs",
    ["order"] = "rs-clean-herbs-035",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/clean_dwarf_weed.png",
    ["rs_name"] = "clean_dwarf_weed",
    ["name"] = "rs-clean-dwarf-weed",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 42,
    ["low_alch"] = 28,
    ["examine"] = "A fresh herb.",
    ["locale_name"] = "Clean dwarf weed",
  },
  ["Torstol seed"] = {
    ["subgroup"] = "rs-herb-seeds",
    ["order"] = "rs-seeds-036-torstol-seed",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/torstol_seed.png",
    ["rs_name"] = "torstol_seed",
    ["name"] = "rs-torstol-seed",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 38,
    ["low_alch"] = 25,
    ["examine"] = "A torstol seed - plant in a herb patch.",
    ["locale_name"] = "Torstol seed",
  },
  ["Grimy torstol"] = {
    ["subgroup"] = "rs-grimy-herbs",
    ["order"] = "rs-grimy-herbs-036",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/grimy_torstol.png",
    ["rs_name"] = "grimy_torstol",
    ["name"] = "rs-grimy-torstol",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 0,
    ["low_alch"] = 0,
    ["examine"] = "I need to clean this herb before I can use it.",
    ["locale_name"] = "Grimy torstol",
  },
  ["Clean torstol"] = {
    ["subgroup"] = "rs-clean-herbs",
    ["order"] = "rs-clean-herbs-036",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/clean_torstol.png",
    ["rs_name"] = "clean_torstol",
    ["name"] = "rs-clean-torstol",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 45,
    ["low_alch"] = 30,
    ["examine"] = "A fresh herb.",
    ["locale_name"] = "Clean torstol",
  },
  ["Arbuck seed"] = {
    ["subgroup"] = "rs-herb-seeds",
    ["order"] = "rs-seeds-037-arbuck-seed",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/arbuck_seed.png",
    ["rs_name"] = "arbuck_seed",
    ["name"] = "rs-arbuck-seed",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 38,
    ["low_alch"] = 25,
    ["examine"] = "An arbuck seed - plant in a herb patch.",
    ["locale_name"] = "Arbuck seed",
  },
  ["Grimy arbuck"] = {
    ["subgroup"] = "rs-grimy-herbs",
    ["order"] = "rs-grimy-herbs-037",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/grimy_arbuck.png",
    ["rs_name"] = "grimy_arbuck",
    ["name"] = "rs-grimy-arbuck",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 60,
    ["low_alch"] = 40,
    ["examine"] = "I need to clean this herb before I can use it.",
    ["locale_name"] = "Grimy arbuck",
  },
  ["Clean arbuck"] = {
    ["subgroup"] = "rs-clean-herbs",
    ["order"] = "rs-clean-herbs-037",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/clean_arbuck.png",
    ["rs_name"] = "clean_arbuck",
    ["name"] = "rs-clean-arbuck",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 90,
    ["low_alch"] = 60,
    ["examine"] = "A fresh herb.",
    ["locale_name"] = "Clean arbuck",
  },
  ["Fellstalk seed"] = {
    ["subgroup"] = "rs-herb-seeds",
    ["order"] = "rs-seeds-038-fellstalk-seed",
    ["stack_size"] = 200,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/fellstalk_seed.png",
    ["rs_name"] = "fellstalk_seed",
    ["name"] = "rs-fellstalk-seed",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 38,
    ["low_alch"] = 25,
    ["examine"] = "A fellstalk seed - plant in a herb patch.",
    ["locale_name"] = "Fellstalk seed",
  },
  ["Grimy fellstalk"] = {
    ["subgroup"] = "rs-grimy-herbs",
    ["order"] = "rs-grimy-herbs-038",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/grimy_fellstalk.png",
    ["rs_name"] = "grimy_fellstalk",
    ["name"] = "rs-grimy-fellstalk",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 60,
    ["low_alch"] = 40,
    ["examine"] = "I need to clean this herb before I can use it.",
    ["locale_name"] = "Grimy fellstalk",
  },
  ["Clean fellstalk"] = {
    ["subgroup"] = "rs-clean-herbs",
    ["order"] = "rs-clean-herbs-038",
    ["stack_size"] = 100,
    ["icon_size"] = 32,
    ["icon"] = "__RsFarming__/graphics/icons/auto_generated/clean_fellstalk.png",
    ["rs_name"] = "clean_fellstalk",
    ["name"] = "rs-clean-fellstalk",
    ["type"] = "item",
    ["flags"] = {
    },
    ["high_alch"] = 90,
    ["low_alch"] = 60,
    ["examine"] = "A fresh herb.",
    ["locale_name"] = "Clean fellstalk",
  },
}